### ISSUE TITLE
lack of clear error message re: cause of java.lang.NullPointerException when Timesteps are not compatible across datasets

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#102]
When the user requests that VERDI take a difference between two variables in different datasets when the datasets do not have the same timesteps, then an error occurs.
In VERDI_1.4.1, the error message gave a clear indication of why an error was obtained.
In subsequent versions, VERDI 1.5.0  and in the current code on github for VERDI_1.6.0_shapefile_mpas, the timestep check is not done, and the reason for the error isn't explained to the user.

----message provide by VERDI_1.4.1----
_**: trowable - Time steps are not compatible across datasets**
2016-09-29 02:05:10,479 [main] ERROR MessageCenter.INTERNAL.anl.verdi.core.VerdiApplication Formula 'CO[1]-CO[2]' is invalid
anl.verdi.formula.IllegalFormulaException: Time steps are not compatible across datasets
    at anl.verdi.formula.FormulaValidator.checkTime(FormulaValidator.java:115)
    at anl.verdi.formula.FormulaValidator.validate(FormulaValidator.java:49)
    at anl.verdi.formula.DefaultFormula.validate(DefaultFormula.java:142)
    at anl.verdi.core.VerdiApplication.create(VerdiApplication.java:746)
    at anl.verdi.commandline.task.TilePlotTask.createFormula(TilePlotTask.java:177)
    at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:65)
    at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:127)
    at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:110)
    at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:108)
    at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:64)
    at saf.core.runtime.CorePlugin.run(CorePlugin.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at saf.core.runtime.Boot.run(Boot.java:86)
    at saf.core.runtime.Boot.main(Boot.java:169)_

----start of message provided by VERDI 1.5.0 and VERDI 1.6.0_shapefile_mpas, VERDI 1.4.1 also has this portion of the message but it also has the above information that describes the reason for the error---
java.lang.NullPointerException
    at anl.verdi.gui.FormulaListModel.addFormula(FormulaListModel.java:56)
    at anl.verdi.commandline.task.TilePlotTask.createFormula(TilePlotTask.java:178)
    at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:65)
    at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:127)
    at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:110)
    at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:108)
    at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:64)
    at saf.core.runtime.CorePlugin.run(CorePlugin.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at saf.core.runtime.Boot.run(Boot.java:86)
    at saf.core.runtime.Boot.main(Boot.java:169)

**Comment by lizadams** [comment]
This doesn't improve if you change the ./plugins/bootstrap/lib/log4j2.xml from ERROR to DEBUG.

**Comment by lizadams** [comment]
Check DefaultFormula.java between version 1.4.1 and (1.50 and 1.6alpha) to see if there is a difference in how it checks for and provides error messages if the dataset time ranges don't match.

**Comment by lizadams** [comment]
tested using the following script, then added O3[2]-O3[1] in the gui.
VERDI gave a pop-up window saying that the timesteps were not compatible across the datasets.
Closing this bug, as VERDI properly gives the user an indication of what is wrong.

```
#!/bin/csh -f
#script for testing command line options
echo 'running verdi_script.csh'
foreach species ( O3 )
./verdi.sh \
         -f $cwd/data/model/CCTM_ACONC_v53_intel_SE53BENCH_20160701.nc \
         -f $cwd/data/model/CCTM_ACONC_v53_intel_SE53BENCH_20160702.nc \
         -s "${species}[1]" \
         -s "${species}[2]" \
         -g tile \
         -saveImage "jpg" $cwd/test.$species.png \
 #         -quit
 end
```
<img width="1170" alt="Screen Shot 2019-06-25 at 3 48 24 PM" src="https://user-images.githubusercontent.com/1183863/60128539-e66bf480-9760-11e9-85a0-68268d161b1c.png">
