### ISSUE TITLE
tile plot of WRF T2 with U10 and V10 wind vector overlay throws an error

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#109]
Wanted to compare a NCL plot of T2 with wind vectors to a VERDI plot.
Created the test script: verdi_script_wrf_d03_t2_wind_vectors
When I added the U10 and V10 as wind vectors, I obtained the following error:

This is the standard output information about the projection that I added to netCDF java library:
The projection in WRFConvention.java is LambertConformal{earth_radius=6370.0, lat0=39.999996185302734, lon0=-97.0, par1=33.0, par2=45.0, falseEasting=0.0, falseNorthing=0.0}

This is the error:
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: ucar.ma2.ArrayFloat$D3 cannot be cast to ucar.ma2.ArrayFloat$D4
    at anl.verdi.data.DataUtilities.unitVectorTransform(DataUtilities.java:441)
    at anl.verdi.core.VerdiApplication.overlayRequested(VerdiApplication.java:844)
    at anl.verdi.plot.probe.PlotEventProducer.fireOverlayRequest(PlotEventProducer.java:35)
    at anl.verdi.plot.gui.FastTilePlot.addVectorOverlay(FastTilePlot.java:2093)
    at anl.verdi.plot.gui.FastTilePlot$15.actionPerformed(FastTilePlot.java:2069)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lizadams** [comment]
NCL plot of T2 and with vector overlay with U10 and V10
![ncl_wrf_t2_wind_vectors_u10_v10](https://cloud.githubusercontent.com/assets/1183863/19406230/3ed09c2a-9250-11e6-9f8c-c5f778c64def.png)

Only able to plot T2 using VERDI, as when I tried to create a vector overlay, it threw an error.
![verdi_wrf_t2](https://cloud.githubusercontent.com/assets/1183863/19406252/bd8b6a18-9250-11e6-8f5d-5c9b9badc65d.png)

**Comment by lizadams** [comment]
Used VERDI Probe to see the lat/lon values for the 4 corners
There is some disagreement over what the value should be.  VERDI is reporting it to be 36.8135N and 109.04521W
![verdi_four_corners_lat_lon](https://cloud.githubusercontent.com/assets/1183863/19406607/32daab0c-9257-11e6-9d78-4be08d95ae15.png)


http://www.dvorak.org/blog/2009/04/20/four-corners-usa-marker-discovered-to-be-off-by-25-miles/

**Comment by joellenb** [comment]
I believe that the error means that VERDI is being given a 3-dimensional ArrayFloat. VERDI expects a 4-dimensional Array Float.
VERDI cannot convert the 3-dimensional structure to the 4-dimensional structure that it needs.

To track this down, start in the code at line 441 in the source code class anl.verdi.data.DataUtilities

Jo Ellen

**Comment by joellenb** [comment]
The longitude matches that article, which computes to 36.99898 degrees latitude, -109.0452 degrees longitude.

Jo Ellen

**Comment by lizadams** [comment]
confirmed error plotting U10 and V10 as wind vectors on T2 Tile Plot as a wind overlay.
This may be a user error, as I am able to plot U and V vectors as wind on the T2 Tile Plot as an overlay.
<img width="1133" alt="Screen Shot 2019-06-26 at 10 28 36 AM" src="https://user-images.githubusercontent.com/1183863/60188408-38faee80-97fd-11e9-8c5a-940e924cc15d.png">
