### ISSUE TITLE
mpas - error occurred while rendering Scatter Plot in VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#119]
dataset: history.2013-07-10.1step.nc
Note, this dataset is available on the following google drive location: https://drive.google.com/drive/u/1/folders/1sKT7YxdqNEIBer5UiK1tJn24U9gVXfAp
variables: rainnc(mm) versus precipw(kg/m2)
Note: the scatter plot works if I try to plot a variable versus itself (rho vs rho)
The scatter plot worked for (sh20 vs smois) so perhaps an error is thrown when the variables have different units??
I tried sst(K) versus skintemp(K) and it didn't work - threw the same error.
RHO(kg/m3) versus THETA(K) worked - they have different units, but they both have the following dimensions:
float rho(Time, nCells, nVertLevels) ;
float theta(Time, nCells, nVertLevels) ;
Other variables have the following dimensions:
        float skintemp(Time, nCells) ;
        float snow(Time, nCells) ;
        float snowh(Time, nCells) ;
        float sst(Time, nCells) ;
        float sh2o(Time, nCells, nSoilLevels) ;
        float smois(Time, nCells, nSoilLevels) ;

![verdi_1 6_shapefile_mpas_mpas history 2013-07-10 1step smoisvssh2o scatter](https://cloud.githubusercontent.com/assets/1183863/19417687/52560992-9381-11e6-95d2-df33a16e9fca.png)

netcdfdataset.java ready to return openDataset 5 arguments
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at anl.verdi.plot.data.ScatterXYDataset$FrameData.<init>(ScatterXYDataset.java:50)
    at anl.verdi.plot.data.ScatterXYDataset$SeriesData.<init>(ScatterXYDataset.java:81)
    at anl.verdi.plot.data.ScatterXYDataset.addSeries(ScatterXYDataset.java:110)
    at anl.verdi.plot.types.ScatterPlot.<init>(ScatterPlot.java:136)
    at anl.verdi.plot.types.ScatterPlot.<init>(ScatterPlot.java:124)
    at anl.verdi.plot.gui.PlotFactory.getScatterPlot(PlotFactory.java:54)
    at anl.verdi.plot.gui.ScatterPlotCreator.doCreatePlot(ScatterPlotCreator.java:57)
    at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39)
    at anl.verdi.plot.gui.action.ScatterPlot.actionPerformed(ScatterPlot.java:21)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lizadams** [comment]
public FrameData(DataFrame frame, int timeStep, int layer) {
			this.frame = frame;
			index = frame.getIndex();
			if (frame.getAxes().getZAxis() == null) {
				index.setTime(timeStep);
			} else {
				if (index instanceof MPASDataFrameIndex) {
					((MPASDataFrameIndex)index).set(timeStep,  layer,  0);
					xExtent = frame.getAxes().getCellAxis().getExtent();
					yExtent = 1;
					return;
				}
				else
					index.set(timeStep, layer, 0, 0);
			}
			**xExtent = frame.getAxes().getXAxis().getExtent();**   ###line 50 where Null pointer exception is thrown
			yExtent = frame.getAxes().getYAxis().getExtent();
		}

**Comment by lizadams** [comment]
![verdi_1 6_shapefile_mpas_mpas history 2013-07-10 1step rhovstheta scatter](https://cloud.githubusercontent.com/assets/1183863/19417774/7d4fb970-9383-11e6-8b79-7caa2cdbdfba.png)

**Comment by lizadams** [comment]
- [x] QA Check to see that the scatter plot works for rainc versus precipw
Confirmed that this does work.
<img width="824" alt="screen shot 2018-12-12 at 1 57 55 pm" src="https://user-images.githubusercontent.com/1183863/49891885-9f965d00-fe15-11e8-9862-23205c94bb56.png">

- [x] QA Check to see that scatter plot was successful for skintemp versus sst
confirmed that this does work
<img width="801" alt="screen shot 2018-12-12 at 2 01 42 pm" src="https://user-images.githubusercontent.com/1183863/49891890-a4f3a780-fe15-11e8-9e05-1bbf205a8a46.png">
