### ISSUE TITLE
mpas - error occurred while rendering a Contour Plot in VERDI

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#120]
Dataset: t2m_only.nc
Variable: t2m

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at anl.verdi.plot.types.Contour3D.createData(Contour3D.java:503)
    at anl.verdi.plot.types.Contour3D.<init>(Contour3D.java:171)
    at anl.verdi.plot.gui.PlotFactory.getPlot(PlotFactory.java:95)
    at anl.verdi.plot.gui.PlotFactory.getPlot(PlotFactory.java:78)
    at anl.verdi.plot.gui.DefaultPlotCreator.doCreatePlot(DefaultPlotCreator.java:48)
    at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39)
    at anl.verdi.plot.gui.action.Contour3DPlot.actionPerformed(Contour3DPlot.java:22)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lizadams** [comment]
testing using VERDI_2.0_beta_linux64_20190623.tar.gz
getting a different error now.
[lizadams@longleaf-login2 VERDI_2.0_beta]$ ./verdi_script_mpas.csh
running verdi_script_mpas.csh
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Java 3D ERROR : glXMakeCurrent fails
extensionStr == null
Canvas3D_createNewContext: couldn't make current

DefaultRenderingErrorListener.errorOccurred:
CONTEXT_CREATION_ERROR: Renderer: Error creating Canvas3D graphics context
graphicsDevice = X11GraphicsDevice[screen=0]
canvas = anl.verdi.plot.util.VerdiCanvas3D[canvas0,0,0,600x625]

**Comment by lizadams** [comment]
this may be due to the t2m variable not having any layers.  
Retried this with precipw variable 
[lizadams@longleaf-login1 VERDI_2.0_beta]$ ./verdi_script_mpas.csh
running verdi_script_mpas.csh
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Java 3D ERROR : glXMakeCurrent fails
extensionStr == null
Canvas3D_createNewContext: couldn't make current

DefaultRenderingErrorListener.errorOccurred:
CONTEXT_CREATION_ERROR: Renderer: Error creating Canvas3D graphics context
graphicsDevice = X11GraphicsDevice[screen=0]
canvas = anl.verdi.plot.util.VerdiCanvas3D[canvas0,0,0,600x625]
ls: cannot access /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta/test.precipw.png: No such file or directory
check outputfile

**Comment by lizadams** [comment]
tested this on a windows machine and it worked!

using VERDI_2.0_beta_win64_20190623

![t2m_contour_plot_windows](https://user-images.githubusercontent.com/1183863/60209914-a7ee3c80-9829-11e9-9a1d-17506e694da4.PNG)

**Comment by jherwehe** [comment]
I originally ran into the libGL errors Liz shows above, but this is not a VERDI problem.  Unlike other VERDI plots, the contour plot in VERDI requires working OpenGL/mesa libraries, which can be tested on a computing platform by typing glxinfo or glxgears (if available).  In my case, I was trying to create a contour plot on VERDI running on _atmos_ via an ssh session from my local Linux workstation, but my workstation's NVIDIA driver was blocking the OpenGL instructions coming through the ssh.  I could always generate a contour plot when VERDI was running locally on my Linux workstation.  Reinstalling the NVIDIA driver on my workstation without its native OpenGL files fixed the problem.  Now VERDI contour plots work on _atmos_ (as does glxgears and the IDV visualization package).  Liz' verdi_script_mpas.csh now generates a contour plot on a Linux platform.  Tests were conducted using the 20190803 version of VERDI_2.0_beta.

Other than the presence of spurious spiky visual noise shown above and raised in #184, this current issue can be closed.
