### ISSUE TITLE
VERDI - out of memory error

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#122]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
    at java.awt.image.Raster.createPackedRaster(Raster.java:467)
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:351)
    at com.apple.laf.AquaPainter$AquaSingleImagePainter.createImage(AquaPainter.java:193)
    at com.apple.laf.AquaPainter$AquaSingleImagePainter.lambda$paintFromSingleCachedImage$279(AquaPainter.java:178)
    at com.apple.laf.AquaPainter$AquaSingleImagePainter$$Lambda$11/291228008.apply(Unknown Source)
    at sun.awt.image.MultiResolutionCachedImage.getResolutionVariant(MultiResolutionCachedImage.java:66)
    at sun.awt.image.MultiResolutionCachedImage.getBaseImage(MultiResolutionCachedImage.java:106)
    at sun.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:82)
    at sun.awt.image.MultiResolutionCachedImage.getWidth(MultiResolutionCachedImage.java:89)
    at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3262)
    at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
    at com.apple.laf.AquaPainter$AquaSingleImagePainter.paintFromSingleCachedImage(AquaPainter.java:186)
    at com.apple.laf.AquaPainter$AquaSingleImagePainter.paint(AquaPainter.java:141)
    at com.apple.laf.AquaPainter.paint(AquaPainter.java:90)
    at com.apple.laf.AquaGroupBorder.paintBorder(AquaGroupBorder.java:68)
    at com.apple.laf.AquaTabbedPaneUI.paintContentBorder(AquaTabbedPaneUI.java:661)
    at com.apple.laf.AquaTabbedPaneUI.paint(AquaTabbedPaneUI.java:134)
    at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    at javax.swing.JComponent.paintComponent(JComponent.java:780)
    at javax.swing.JComponent.paint(JComponent.java:1056)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
Exception in thread "AWT-EventQueue-0" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"
Exception in thread "Thread-24" java.lang.OutOfMemoryError: Java heap space

**Comment by dschwede** [comment]
Some more context on this one would be helpful.  It isn't clear what the issue is.  Users can change the amount of memory available, but at some point they will run out of space.  What is the exact issue?

**Comment by lizadams** [comment]
closing this issue, as I am not sure how to reproduce it.
