### ISSUE TITLE
CAMX d03 grid - 4km comparison between Python and VERDI plots with hu02 watershed boundary

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#124]
VERDI plot:
The data seems to be shifted North. There is a high concentration at the corner of the Utah-Wyoming Border on the Python Plot, that is much further north (by several grid cells).
Actually the HU08 shapefile showing watershed boundaries seems shifted South by 1 grid cell.
![verdi_1 6 0_shapefile_mpas_co_camx_converted_to_cmaq](https://cloud.githubusercontent.com/assets/1183863/19460780/d53e0950-94ac-11e6-8aec-7e7cefcfc6ea.png)

Python Plot using PseudoNetCDF
![co_lay1_camx_converted_to_cmaq_pypnc_d03](https://cloud.githubusercontent.com/assets/1183863/19460784/dedbe824-94ac-11e6-92bd-d1305abdf191.png)

VERDI Plot zoomed, with grid lines (background shapefile of watersheds seems to be shifted south in comparison to the state lines.
Need to check and see if the state boundary file that we are using in VERDI lines up with the state lines used by Python.
![verdi_1 6 0_shapefile_mpas_camx_grd03_co_utah_wyoming](https://cloud.githubusercontent.com/assets/1183863/19461083/7023421c-94af-11e6-8c8a-c5c83bb1d565.png)

**Comment by lizadams** [comment]
Tried using the state shapefile in python that we currently use in VERDI, and ran into an error.
(py3k) cep00159:PseudoNetCDF lizadams$ python tileplot.cmaq_converted_camx.py
Found IO/API Mapping parameters
Traceback (most recent call last):
  File "tileplot.cmaq_converted_camx.py", line 34, in <module>
    map.readshapefile('/Users/lizadams/local_git_repository/VERDI/verdi_bootstrap/data/map_state/cb_2014_us_state_500k', 'state')
  File "//anaconda/envs/py3k/lib/python3.3/site-packages/mpl_toolkits/basemap/__init__.py", line 2152, in readshapefile
    raise ValueError('readshapefile can only handle 2D shape types')
ValueError: readshapefile can only handle 2D shape types
So - can't do a comparison between the state boundary.

Tried to read in the shapefile that we have in VERDI for the background map and also obtained an error.
(py3k) cep00159:PseudoNetCDF lizadams$ python tileplot.cmaq_converted_camx.py
Found IO/API Mapping parameters
Traceback (most recent call last):
  File "tileplot.cmaq_converted_camx.py", line 34, in <module>
    map.readshapefile('/Users/lizadams/local_git_repository/VERDI/verdi_bootstrap/data/map_county/cb_2014_us_county_500k', 'state')
  File "//anaconda/envs/py3k/lib/python3.3/site-packages/mpl_toolkits/basemap/__init__.py", line 2146, in readshapefile
    for shprec in shf.shapeRecords():
  File "//anaconda/envs/py3k/lib/python3.3/site-packages/mpl_toolkits/basemap/shapefile.py", line 543, in shapeRecords
    for rec in zip(self.shapes(), self.records())]
  File "//anaconda/envs/py3k/lib/python3.3/site-packages/mpl_toolkits/basemap/shapefile.py", line 515, in records
    r = self.__record()
  File "//anaconda/envs/py3k/lib/python3.3/site-packages/mpl_toolkits/basemap/shapefile.py", line 491, in __record
    value = u(value)
  File "//anaconda/envs/py3k/lib/python3.3/site-packages/mpl_toolkits/basemap/shapefile.py", line 58, in u
    return v.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4: invalid continuation byte

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz
Found the CAMx set of files used for this test.
Couldn't read the d03 file, but was able to read the d02 file.
using the following script
```
#!/bin/csh -f
#script for testing command line options
echo 'running verdi_script_camx.csh'
foreach species ( O3 )
./verdi.sh \
         -f $cwd/data/CAMx/outputs/camx.v6.10.CB6r2.3SAQS_Base11a_sensWinterO3.25L.2011033.avrg.grd02 \
         -titleString "CAMx GRD02 ${species} Layer 1" \
         -configFile  ~/verdi_config_camx_gr02 \
         -s "${species}[1]" \
         -g tile \
         -saveImage "jpg" $cwd/VERDI.camx.grd02.$species.png \
 #         -quit
 end
```
using pseudoNetCDF on my mac to create a python tileplot: 
https://github.com/barronh/pseudonetcdf/wiki/Tile-Plotting-Tutorial

<img width="641" alt="Screen Shot 2019-06-26 at 1 01 54 PM" src="https://user-images.githubusercontent.com/1183863/60199764-a5341d00-9812-11e9-9808-8904b2a69f15.png">
Note the following image is of timestep 1 - can't specify to use the statistics of average or mean from the command line.  Do note that the min and max values are not captured in the image that was saved by verdi.
<img width="801" alt="Screen Shot 2019-06-26 at 1 01 17 PM" src="https://user-images.githubusercontent.com/1183863/60199765-a5341d00-9812-11e9-897a-4ee60f04e8d2.png">

Difficult to get the VERDI plot window to show both the legend on the side, and the min/max values below the plot. 
The following plot is of the average, and looks more like the python plot.
I don't see a georeferencing issue here, although it is hard to tell without using the same base maps, and similar color scheme for the legend.
<img width="656" alt="Screen Shot 2019-06-26 at 1 05 32 PM" src="https://user-images.githubusercontent.com/1183863/60200022-3905e900-9813-11e9-8acf-5184b1e9502f.png">
