### ISSUE TITLE
contour plot animate gif

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#149]
Changed AnimationPanelContour3D to enable showing option to create an animated gif.
The following is used to disable the option
gifChk.setEnabled(false); 		// 2014
changed to 
gifChk.setEnabled(true); 		// 2014
Used the verdi_script_contour.launch to create a contour plot and select the option to create an animated gif. 
The following error occurred
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.swing.Timer cannot be cast to java.awt.image.BufferedImage
	at anl.verdi.plot.anim.PlotAnimator$UpdatePlotAction.actionPerformed(PlotAnimator.java:209)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lizadams** [comment]
Question is why does VERDI throw this error for the request to animate a 3D Contour Plot but not when a request to animate a Tile Plot.
Information about Buffered Image from VERDI tile plot. Breakpoint at line 210 in PlotAnimator.java

`BufferedImage@79dab260: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 893 height = 668 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0`

For the Tile Plot
java.awt.event.ActionEvent[unknown type,cmd=,when=0,modifiers=] on BufferedImage@49ca5754: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 893 height = 668 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0

For the Contour3D plot
java.awt.event.ActionEvent[unknown type,cmd=,when=0,modifiers=] on BufferedImage@49ca5754: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 893 height = 668 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0


Information about window obtained by setting a breakpoint at line 324.
Need to see if this is the difference between how a Tile Plot and a Contour Plot are handled.
```java
                if (window instanceof JFrame)                        
                        dialog = new JDialog((JFrame) window, "Animate Plot", false);
                else
                        dialog = new JDialog((JDialog) window, "Animate Plot", false);
```

output for window in Contour 3D Plot - Animate Plot

`javax.swing.JFrame[frame0,0,196,700x700,invalid,layout=java.awt.BorderLayout,title=Contour36NO4181,resizable,normal,defaultCloseOperation=HIDE_ON
_CLOSE,rootPane=javax.swing.JRootPane[,0,22,700x678,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=1
6777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=trueHere is the 

output for the window in the Tile Plot - Animate Plot`

`javax.swing.JFrame[frame0,165,23,1275x873,invalid,layout=java.awt.BorderLayout,title=VERDI,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_C
LOSE,rootPane=javax.swing.JRootPane[,0,22,1275x851,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16
777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]`

 At a breakpoint at line 208 in PlotAnimator.java
java.awt.event.ActionEvent[unknown type,cmd=null,when=1487092559711,modifiers=] on javax.swing.Timer@774600a5

**Comment by lizadams** [comment]
The animated plot window may not be properly associated with the Contour3D plot, as the contour3D plot is external to the VERDI main panel.  The swing timer, may be triggered when you click start on the Animate Plot Panel, but rather than sending the name of the Contour3D plot window ID, it is sending it's own id.

**Comment by lizadams** [comment]
related to issue #184
