### ISSUE TITLE
VERDI can't read BCON (boundary condition) input for the CMAQ model

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#15]

**Comment by lizadams** [comment]
Example boundary condition file:

```
wget https://cmas-cmaq.s3.amazonaws.com/CMAQv5.4_2018_12NE3_Benchmark_2Day_Input/2018_12NE3/icbc/CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701.nc
```

Currently, VERDI gives an error:

```
verdi.sh -f $cwd/CMAQv5.4_2018_12NE3_Benchmark_2Day_Input/2018_12NE3/icbc/CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701.nc

```
Error in pop-up window:

No loaders are available for the selected file.

Error at the command line:
2025.04.10 12:29:43.958 [main] ERROR anl.verdi.data.DataManager - No loaders are available for the selected file.

The BCON files use this data structure:
https://www.cmascenter.org/ioapi/documentation/all_versions/html/DATATYPES.html#bndary


Contents of the BCON file:



netcdf CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701 {
dimensions:
	TSTEP = UNLIMITED ; // (25 currently)
	DATE-TIME = 2 ;
	LAY = 35 ;
	VAR = 222 ;
	PERIM = 414 ;
variables:
	int TFLAG(TSTEP, VAR, DATE-TIME) ;
		TFLAG:units = "<YYYYDDD,HHMMSS>" ;
		TFLAG:long_name = "TFLAG           " ;
		TFLAG:var_desc = "Timestep-valid flags:  (1) YYYYDDD or (2) HHMMSS                                " ;
	float NO2(TSTEP, LAY, PERIM) ;
		NO2:long_name = "NO2             " ;
		NO2:units = "ppmV            " ;
		NO2:var_desc = "Instantaneous Molar Mixing Ratio NO2                                            " ;

...

Global attributes

// global attributes:
		:IOAPI_VERSION = "ioapi-3.2: $Id: init3.F90 98 2018-04-05 14:35:07Z coats $                       " ;
		:EXEC_ID = "????????????????                                                                " ;
		:FTYPE = 2 ;
		:CDATE = 2022249 ;
		:CTIME = 171334 ;
		:WDATE = 2022249 ;
		:WTIME = 171334 ;
		:SDATE = 2018182 ;
		:STIME = 0 ;
		:TSTEP = 10000 ;
		:NTHIK = 1 ;
		:NCOLS = 100 ;
		:NROWS = 105 ;
		:NLAYS = 35 ;
		:NVARS = 222 ;
		:GDTYP = 2 ;
		:P_ALP = 33. ;
		:P_BET = 45. ;
		:P_GAM = -97. ;
		:XCENT = -97. ;
		:YCENT = 40. ;
		:XORIG = 1140000. ;
		:YORIG = -456000. ;
		:XCELL = 12000. ;
		:YCELL = 12000. ;
		:VGTYP = 7 ;
		:VGTOP = 5000.f ;
		:VGLVLS = 1.f, 0.9975f, 0.995f, 0.99f, 0.985f, 0.98f, 0.97f, 0.96f, 0.95f, 0.94f, 0.93f, 0.92f, 0.91f, 0.9f, 0.88f, 0.86f, 0.84f, 0.82f, 0.8f, 0.77f, 0.74f, 0.7f, 0.65f, 0.6f, 0.55f, 0.5f, 0.45f, 0.4f, 
0.35f, 0.3f, 0.25f, 0.2f, 0.15f, 0.1f, 0.05f, 0.f ;
		:GDNAM = "2018_12NE3      " ;
		:UPNAM = "BCWNDW          " ;
		:VAR-LIST = "NO2

**Comment by lizadams** [comment]
Additional files that use the same data structure include: METBDY3D and GRIDBDY[2,3]D

Example files for GRIDBDY2D and METBDY3D:

```
wget https://cmas-cmaq.s3.amazonaws.com/CMAQv5.4_2018_12NE3_Benchmark_2Day_Input/2018_12NE3/met/mcipv5.4/GRIDBDY2D_12NE3_20180701.nc
wget https://cmas-cmaq.s3.amazonaws.com/CMAQv5.4_2018_12NE3_Benchmark_2Day_Input/2018_12NE3/met/mcipv5.4/METBDY3D_12NE3_20180701.nc
```

Example command for loading these files into VERDI:

```
verdi.sh -f $cwd/GRIDBDY2D_12NE3_20180701.nc
```

```
verdi.sh -f $cwd/METBDY3D_12NE3_20180701.nc
```

Attempting to load these files gives the same error:

2025.04.10 15:10:24.284 [main] ERROR anl.verdi.data.DataManager - No loaders are available for the selected file.

**Comment by lizadams** [comment]
Retested using the  VERDI_2.2_linux64_20260408.tar.gz build package.
This package was able to load and create a tile plot for the BCON file from the CAMx test package, used in issue https://github.com/CEMPD/VERDI/issues/378 

However, it didn't work for the  CMAQ BCON file provided in this issue:

./verdi.sh -f $cwd/data/model/CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701.nc

 ./verdi.sh -f $cwd/data/model/CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701.nc
[]
2026.04.13 11:37:51.253 [main] ERROR anl.verdi.commandline.ScriptHandler - Exception in ScriptHandler.dataMap.put 'F'
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxes(AbstractNetcdfDataset.java:184) ~[?:?]
	at anl.verdi.gui.DatasetListElement.<init>(DatasetListElement.java:21) ~[core.jar:?]
	at anl.verdi.gui.DatasetListModel.addDataset(DatasetListModel.java:80) ~[core.jar:?]
	at anl.verdi.gui.DataSetPanel.loadDataset(DataSetPanel.java:662) ~[core.jar:?]
	at anl.verdi.core.VerdiGUI.loadDataset(VerdiGUI.java:471) ~[core.jar:?]
	at anl.verdi.core.VerdiApplication.loadDataset(VerdiApplication.java:658) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler$2.run(ScriptHandler.java:222) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1528) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:167) [core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:168) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:178) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:388) [saf.core.runtime.jar:?]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at anl.verdi.loaders.AbstractNetcdfDataset.getCoordAxes(AbstractNetcdfDataset.java:184)
	at anl.verdi.gui.DatasetListElement.<init>(DatasetListElement.java:21)
	at anl.verdi.gui.DatasetListModel.addDataset(DatasetListModel.java:80)
	at anl.verdi.gui.DataSetPanel.loadDataset(DataSetPanel.java:662)
	at anl.verdi.core.VerdiGUI.loadDataset(VerdiGUI.java:471)
	at anl.verdi.core.VerdiApplication.loadDataset(VerdiApplication.java:658)
	at anl.verdi.commandline.ScriptHandler$2.run(ScriptHandler.java:222)
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1528)
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:167)
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:168)
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93)
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at saf.core.runtime.Boot.run(Boot.java:178)
	at saf.core.runtime.Boot.main(Boot.java:388)

**Comment by lizadams** [comment]
Is the failure because COL and ROW are not defined as dimensions, with only PERIM defined in the BCON file created for CMAQ?

Is there a way for VERDI to get COL and ROW from the global attributes NCOLS and NROWS?

The CAMx bcon file contains the following dimensions:

	ncdump $cwd/../../CAMx_test_case/icbc/bc.36km.20160611.nc | more

netcdf bc.36km.20160611 {
dimensions:
	TSTEP = UNLIMITED ; // (4 currently)
	DATE-TIME = 2 ;
	LAY = 20 ;
	VAR = 57 ;
	ROW = 91 ;
	COL = 158 ;

with global attributes:
		:NCOLS = 158 ;
		:NROWS = 91 ;
		:NLAYS = 20 ;



The CMAQ bcon file contains:

     ncdump $cwd/data/model/CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701.nc | more

netcdf CCTM_BCON_v54_cb6r5_ae7_aq_12NE3_20180701 {
dimensions:
	TSTEP = UNLIMITED ; // (25 currently)
	DATE-TIME = 2 ;
	LAY = 35 ;
	VAR = 222 ;
	PERIM = 414 ;

with global attributes:
		:NCOLS = 100 ;
		:NROWS = 105 ;
		:NLAYS = 35 ;
		:NVARS = 222 ;


Or is the issue that the PERIM dimension is not available as a global attribute?

Or is it an off by 1 error? Looking for an index value that doesn't exist?

https://docs.unidata.ucar.edu/netcdf-java/5.8/userguide/coord_attribute_ex.html#coordinate-variables-and-aliases

It is failing on line 184 here:
https://github.com/CEMPD/VERDI/blob/master/verdi_data_loaders/src/anl/verdi/loaders/AbstractNetcdfDataset.java#L181C2-L198C20


public Axes<CoordAxis> getCoordAxes() {
		if (coordAxes == null) {
			List<CoordAxis> list = new ArrayList<CoordAxis>();
			GridDatatype grid = (GridDatatype) gridDataset.getGrids().get(0);      ### line 184
			GridCoordSystem system = grid.getCoordinateSystem();
			List<CoordinateAxis> coords = system.getCoordinateAxes();
			for (CoordinateAxis axis : (List<CoordinateAxis>) coords) {
				ucar.nc2.constants.AxisType ncfType = axis.getAxisType();
				if (ncfType != null) {
					AxisType type = types.get(ncfType);
					if (type == null)
						type = AxisType.OTHER;
					list.add(new NetCdfCoordAxis(axis, type));
				}
			}
			coordAxes = new Axes<CoordAxis>(list, new NetcdfBoxer(grid));
		}
		return coordAxes;


java.util.List<[GridDatatype](https://docs.unidata.ucar.edu/netcdf-java/4.6/javadoc/ucar/nc2/dt/GridDatatype.html)> 	[getGrids](https://docs.unidata.ucar.edu/netcdf-java/4.6/javadoc/ucar/nc2/dt/grid/GridDataset.html#getGrids--)()
get the list of GridDatatype objects contained in this dataset.

https://docs.unidata.ucar.edu/netcdf-java/4.6/userguide/tutorial/GridDatatype.html
