### ISSUE TITLE
Probe giving incorrect values for Lat/long file

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#180]
A user was viewing a lat/long file which seemed to display correctly, but the probe was giving incorrect values. 

From the user: 
Here is the NCEP/CPC file (acquired from NOAA/ESRL) that is in netCDF format containing global daily precipitation on a 0.5-degree latitude-longitude grid:

     /home/jherwehe/mpas/download/ncep/cpc/cpc_global_daily_precip.2016.nc

The data are globally landmasked via a defined missing_value = -9.96921e+036, which the NetCDF Operators (NCO) and the current alpha version of VERDI both seem to handle fine.

**Comment by lizadams** [comment]
Note: when I tried to load this file, I would get the following error.
2018.12.13 14:50:41.582 [AWT-EventQueue-0] ERROR anl.verdi.plot.gui.action.FastTilePlot - An error occurred while rendering the plot
java.lang.OutOfMemoryError: Java heap space
        at ucar.ma2.ArrayDouble.<init>(ArrayDouble.java:82) ~[netcdfAll-4.5.5-SNAPSHOT.jar:4.5.5-SNAPSHOT]
        at ucar.ma2.ArrayDouble$D3.<init>(ArrayDouble.java:306) ~[netcdfAll-4.5.5-SNAPSHOT.jar:4.5.5-SNAPSHOT]
        at anl.verdi.util.ArrayFactory.createDoubleArray(ArrayFactory.java:97) ~[?:?]
        at anl.verdi.data.DataUtilities.createDataFrame(DataUtilities.java:378) ~[?:?]
        at anl.verdi.plot.gui.FastTilePlot.calculateDataFrameLog(FastTilePlot.java:3658) ~[?:?]
        at anl.verdi.plot.gui.FastTilePlot.<init>(FastTilePlot.java:1341) ~[?:?]
        at anl.verdi.plot.gui.action.FastTilePlot.actionPerformed(FastTilePlot.java:54) ~[?:?]

My workaround was to restrict the Time Steps to using a Time Range of only 1-24, rather than the full range of 1-366.

I am not sure how the lat/lon values were tested.  
I zoomed into the 4 corners region, and used the probe to see the lat/lon values and obtained 36.99N and 109.04W
This appears to agree with 
https://latitude.to/articles-by-country/us/united-states/1707/four-corners
36.9927152491 -109.040436537

Based on this, I am going to close this bug.
