### ISSUE TITLE
MPAS Vertical cross section plots

### ISSUE THREAD

**Issue by dschwede** [CEMPD/VERDI#181]
Vertical cross section tile plots sort of work, but look odd (i.e., not rectangular cell tiles).

**Comment by lizadams** [comment]
Using VERDI_2.0_beta_linux64_20190623.tar.gz I am getting an error using the following script to load the dataset, and then using the GUI to create the vertical cross section plot

```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_mpas.csh'
setenv verdi_dir /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
cd $verdi_dir

foreach species ( t2m )
./verdi.sh \
#         -f $verdi_dir/data/model/history.2013-07-10.nc \
          -f $verdi_dir/data/model/t2m_only.nc \
#          -configFile $verdi_dir/data/configs/10bin_new_config \
#         -legendBins ".008,.016,.024,.032,.04,.048,.056,.064,.072,.08" \
#         -titleString "CMAQv46 ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
#         -saveImage "jpg" $verdi_dir/test.$species.png \
#         -animatedGIF $verdi_dir/test.$species.gif \
#          -quit
          echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.png`
         # echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.gif`
 end

```

[lizadams@longleaf-login2 VERDI_2.0_beta]$ ./verdi_script_mpas.csh
running verdi_script_mpas.csh
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at anl.verdi.plot.types.VerticalCrossSectionPlot$LayerAxisFormatter.<init>(VerticalCrossSectionPlot.java:699)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.createIntegerTickUnits(VerticalCrossSectionPlot.java:478)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.createChart(VerticalCrossSectionPlot.java:423)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:172)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:112)
	at anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot(PlotFactory.java:111)
	at anl.verdi.plot.gui.VerticalCrossPlotCreator.createVertPlot(VerticalCrossPlotCreator.java:127)
	at anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(VerticalCrossPlotCreator.java:93)
	at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39)
	at anl.verdi.plot.gui.action.VerticalCrossSection.actionPerformed(VerticalCrossSection.java:21)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at anl.verdi.plot.types.VerticalCrossSectionPlot$LayerAxisFormatter.<init>(VerticalCrossSectionPlot.java:699)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.createIntegerTickUnits(VerticalCrossSectionPlot.java:478)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.createChart(VerticalCrossSectionPlot.java:423)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:172)
	at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:112)
	at anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot(PlotFactory.java:111)
	at anl.verdi.plot.gui.VerticalCrossPlotCreator.createVertPlot(VerticalCrossPlotCreator.java:127)
	at anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(VerticalCrossPlotCreator.java:93)
	at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39)
	at anl.verdi.plot.gui.action.VerticalCrossSection.actionPerformed(VerticalCrossSection.java:21)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by lizadams** [comment]
This error is generated because the variable t2m doesn't have any layers.  Closing this bug.
