### ISSUE TITLE
mac version ERROR

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#188]
I am getting the following error on the mac using this version: VERDI_1.6.0_alpha_mac_20180918.tar.gz
Note: I also had to install the jdk prior to running VERDI.
First I had to create a folder for the verdi.log under
/Users/lizadams/verdi/
Then I had to set the following environment variable VERDI_USER=/Users/lizadams
I also edited the  plugins/bootstrap/lib/log4j2.xml file to change ERROR to DEBUG, although this probably wasn't necessary.  I did this when I couldn't get the verdi.log file to generate.  There was no warning at the command line that there was an error, just a return of the prompt, with no VERDI window being generated.

Here is the error I am seeing towards the end of the verdi.log file:
2018.09.26 10:17:55.324 [main] WARN  org.java.plugin.standard.StandardPluginClassLoader - class not visible, no class filter found, lib=file:/Users/lizadams/VERDI_1.6.0_alpha/plugins/saf.core.ui/saf.core.ui.jar, class=interface saf.core.ui.IAppConfigurator, this={PluginClassLoader: uid=1192672907; {PluginDescriptor: uid=saf.core.ui@1.0.0}}, requestor={PluginClassLoader: uid=1426435610; {PluginDescriptor: uid=anl.verdi@1.0.0}}
2018.09.26 10:17:55.324 [main] ERROR saf.core.runtime.Boot - caught an InvocationTargetException in Boot.run
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at saf.core.runtime.Boot.run(Boot.java:160) [saf.core.runtime.jar:?]
        at saf.core.runtime.Boot.main(Boot.java:333) [saf.core.runtime.jar:?]
Caused by: java.lang.NoClassDefFoundError: saf/core/ui/IAppConfigurator
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138) ~[?:?]
        at java.base/java.lang.Class.getConstructor0(Class.java:3343) ~[?:?]
        at java.base/java.lang.Class.newInstance(Class.java:556) ~[?:?]
        at org.java.plugin.standard.StandardPluginLifecycleHandler.createPluginInstance(StandardPluginLifecycleHandler.java:122) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginManager.activatePlugin(StandardPluginManager.java:403) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginManager.getPlugin(StandardPluginManager.java:217) ~[jpf.jar:1.5.1]
        at saf.core.runtime.CorePlugin.loadAppPlugin(CorePlugin.java:86) ~[saf.core.runtime.jar:?]
        at saf.core.runtime.CorePlugin.run(CorePlugin.java:42) ~[saf.core.runtime.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: class saf.core.ui.IAppConfigurator is not visible for plug-in anl.verdi, no filter found for library file:/Users/lizadams/VERDI_1.6.0_alpha/plugins/saf.core.ui/saf.core.ui.jar
        at org.java.plugin.standard.StandardPluginClassLoader.checkClassVisibility(StandardPluginClassLoader.java:611) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginClassLoader.loadPluginClass(StandardPluginClassLoader.java:466) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginClassLoader.loadPluginClass(StandardPluginClassLoader.java:491) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginClassLoader.loadClass(StandardPluginClassLoader.java:372) ~[jpf.jar:1.5.1]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138) ~[?:?]
        at java.base/java.lang.Class.getConstructor0(Class.java:3343) ~[?:?]
        at java.base/java.lang.Class.newInstance(Class.java:556) ~[?:?]
        at org.java.plugin.standard.StandardPluginLifecycleHandler.createPluginInstance(StandardPluginLifecycleHandler.java:122) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginManager.activatePlugin(StandardPluginManager.java:403) ~[jpf.jar:1.5.1]
        at org.java.plugin.standard.StandardPluginManager.getPlugin(StandardPluginManager.java:217) ~[jpf.jar:1.5.1]
        at saf.core.runtime.CorePlugin.loadAppPlugin(CorePlugin.java:86) ~[saf.core.runtime.jar:?]
        at saf.core.runtime.CorePlugin.run(CorePlugin.java:42) ~[saf.core.runtime.jar:?]
        ... 6 more

**Comment by lizadams** [comment]
Obtained the new build Tony provided on atmos.
VERDI_1.6.0_alpha_mac_20181003.tar.gz

It worked once I edited the verdi.command file to point to the location of java in the package.
If this is the correct fix, then it needs to be updated in the code.
#JAVA=../../jre/Commands/java
JAVA=../../jre/Contents/Home/jre/bin/java

**Comment by lizadams** [comment]
Fixed verdi.command path to find the pre-installed java command with issue a7aefaf
