### ISSUE TITLE
tileplot> show wind vectors - MPAS tileplot error

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#197]
VERDI throws a null pointer exception when the user selects the following:
./verdi.command -f /applications/VERDI_2.0_beta/data/model/t2m_only.nc
Select variable t2m, create tile plot
Controls> Show Wind Vectors

(py36) Elizabeths-MBP:VERDI_2.0_beta lizadams$ ./verdi.command
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
java.lang.NullPointerException
	at anl.verdi.loaders.MPASDataset$CellInfo.getZonal(MPASDataset.java:247)
	at anl.verdi.plot.gui.MeshPlot$LocalCellInfo.calculateWindVector(MeshPlot.java:1732)
	at anl.verdi.plot.gui.MeshPlot.updateWindData(MeshPlot.java:2107)
	at anl.verdi.plot.gui.MeshPlot$7.run(MeshPlot.java:697)
	at java.lang.Thread.run(Thread.java:745)

Note: The option to create Wind Vectors from the TilePlot window is different for MPAS files than for other files.  This change will be difficult to document, it would be better if the options available for the MPAS Tileplot mirrored other Tileplot options.

For the Tileplot created after loading a CMAQ output file.
Menu Options to create vectors is under:
Plot > Add Overlay > Vectors

(Note that this is the same method used to add Observations, which the MPAS Tileplot doesn't currently support) Plot > Add Overlay > Observations

For the Tileplot created after loading a MPAS output file.
Menu Options to create vectors is:
Controls > Show Wind Vectors

- [ ] Recommend changing the MPAS Tileplot to be consistent with the other tileplots.

**Comment by lizadams** [comment]
Note: the MPAS dataset used for testing this: t2m_only.nc 
contained the temperature variable only, not the wind variables, so that is why the error occurred.
Retried this using the full history file: history.2013-07-10.nc 
available from the following google drive https://drive.google.com/drive/u/0/folders/1ykwOX9h7YwB07bX7fD7wNOmCkLOJPSDb
and verified that it works correctly. 
```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_mpas.csh'
setenv verdi_dir /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
cd $verdi_dir

foreach species ( t2m )
./verdi.sh \
         -f $verdi_dir/data/model/history.2013-07-10.nc \
#          -configFile $verdi_dir/data/configs/10bin_new_config \
#         -legendBins ".008,.016,.024,.032,.04,.048,.056,.064,.072,.08" \
#         -titleString "CMAQv46 ${species} Layer 1" \
         -s "${species}[1]" \
         -g tile \
#         -saveImage "jpg" $verdi_dir/test.$species.png \
#         -animatedGIF $verdi_dir/test.$species.gif \
#          -quit
          echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.png`
         # echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.gif`
 end
```
This file is not provided in the VERDI data directory as it is too large (17.1 GB)
It would be ideal to create a small dataset with both temperature and the wind variables and provide it with VERDI.

<img width="1161" alt="Screen Shot 2019-06-24 at 5 59 24 PM" src="https://user-images.githubusercontent.com/1183863/60054883-dd6c1c00-96a9-11e9-8f70-99fc201c9f82.png">

Note, there isn't an option to reduce the number of wind vectors shown on the plot.
You can zoom in on a region, and the wind vectors can be seen more clearly.

<img width="555" alt="Screen Shot 2019-06-24 at 6 00 11 PM" src="https://user-images.githubusercontent.com/1183863/60054951-0db3ba80-96aa-11e9-807a-a669ca7b7d75.png">
