### ISSUE TITLE
Error rendering FastTilePlot of multiple variables from the command line

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#203]
Command line error using the VERDI_2.0_beta_mac_20190521.tar.gz version, but it also occurred with earlier versions.

This verdi command should load 2 variables and create 2 tile plots, but it gives an error:
```
./verdi.command -f $cwd/data/model/CCTM_combine.2008031.dave.nc.1 -f $cwd/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile 
```
```
2019.05.29 16:31:38.368 [Thread-5] ERROR anl.verdi.plot.gui.FastTilePlot - Error rendering FastTilePlot
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:400) ~[?:1.7.0_79]
	at java.util.ArrayList.get(ArrayList.java:413) ~[?:1.7.0_79]
	at bibliothek.gui.dock.station.stack.DefaultStackDockComponent.getDockableAt(Unknown Source) ~[dockingFramesCore.jar!/:?]
	at saf.core.ui.dock.DefaultDockableFrame.isHidden(DefaultDockableFrame.java:132) ~[saf.core.ui.jar!/:?]
	at anl.verdi.core.VerdiGUI.isHidden(VerdiGUI.java:255) ~[core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:413) [core.jar!/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
```

<img width="435" alt="verdi_error" src="https://user-images.githubusercontent.com/1183863/58590152-733e9380-8231-11e9-958c-426a991d3e25.png">

The following verdi command should load 2 variables and one formula and create 3 tile plots, but it gives an error.

```
./verdi.sh -f $cwd/data/model/CCTM_combine.2008031.dave.nc.1 -f $cwd/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile -s "O3[1]-O3[2]" -g tile
```

Output:

```
2019.05.29 16:28:19.804 [Thread-5] ERROR anl.verdi.plot.gui.FastTilePlot - Error rendering FastTilePlot
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:400) ~[?:1.7.0_79]
	at java.util.ArrayList.get(ArrayList.java:413) ~[?:1.7.0_79]
	at bibliothek.gui.dock.station.stack.DefaultStackDockComponent.getDockableAt(Unknown Source) ~[dockingFramesCore.jar!/:?]
	at saf.core.ui.dock.DefaultDockableFrame.isHidden(DefaultDockableFrame.java:132) ~[saf.core.ui.jar!/:?]
	at anl.verdi.core.VerdiGUI.isHidden(VerdiGUI.java:255) ~[core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:413) [core.jar!/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at javax.swing.JTabbedPane.getBackgroundAt(JTabbedPane.java:1179)
	at com.apple.laf.AquaTabbedPaneUI.paintCUITab(AquaTabbedPaneUI.java:463)
	at com.apple.laf.AquaTabbedPaneUI.paintTabNormalFromRect(AquaTabbedPaneUI.java:416)
	at com.apple.laf.AquaTabbedPaneUI.paintTabNormal(AquaTabbedPaneUI.java:409)
	at com.apple.laf.AquaTabbedPaneUI.paintAllTabs(AquaTabbedPaneUI.java:161)
	at com.apple.laf.AquaTabbedPaneUI.paint(AquaTabbedPaneUI.java:151)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:779)
	at javax.swing.JComponent.paint(JComponent.java:1055)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JComponent.paintChildren(JComponent.java:888)
	at javax.swing.JComponent.paint(JComponent.java:1064)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5232)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1529)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1452)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5180)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4991)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
	at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by lizadams** [comment]
Getting a similar error using most recent linux build.
```
./verdi.sh -version                                                                                                        Version: 2.0_beta 2019-06-10
```
./verdi.sh -f $cwd/data/model/CCTM_combine.2008031.dave.nc.1 -f $cwd/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile -s "O3[1]-O3[2]" -g tile
2019.06.10 13:57:04.034 [Thread-5] ERROR anl.verdi.plot.gui.FastTilePlot - Error rendering FastTilePlot
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_79]
	at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_79]
	at bibliothek.gui.dock.station.stack.DefaultStackDockComponent.getDockableAt(Unknown Source) ~[dockingFramesCore.jar!/:?]
	at saf.core.ui.dock.DefaultDockableFrame.isHidden(DefaultDockableFrame.java:133) ~[saf.core.ui.jar!/:?]
	at anl.verdi.core.VerdiGUI.isHidden(VerdiGUI.java:255) ~[core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:415) [core.jar!/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

<img width="1016" alt="Screen Shot 2019-06-10 at 2 19 02 PM" src="https://user-images.githubusercontent.com/1183863/59215721-f217c280-8b87-11e9-83d8-f09a2a8644ac.png">

**Comment by lizadams** [comment]
Tested using VERDI_2.0_beta_linux64_20190623.tar.gz
Still getting an error, but the plot is able to be generated.
<img width="858" alt="Screen Shot 2019-06-24 at 1 46 48 PM" src="https://user-images.githubusercontent.com/1183863/60040347-c49e3f00-9686-11e9-931e-8e126968bc9e.png">

**Comment by lizadams** [comment]
retested using VERDI_2.1_mac_20211206.tar.gz, and am still seeing the same behavior and error message.
The second plot looks ok, but the first one does not get created.

> ./verdi.command -f $cwd/data/model/CCTM_combine.2008031.dave.nc.1 -f 
$cwd/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
2021.12.08 15:41:43.876 [Thread-3] ERROR anl.verdi.plot.gui.FastTilePlot - Error rendering FastTilePlot
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at bibliothek.gui.dock.station.stack.DefaultStackDockComponent.getDockableAt(Unknown Source) ~[dockingFramesCore.jar:?]
	at saf.core.ui.dock.DefaultDockableFrame.isHidden(DefaultDockableFrame.java:135) ~[saf.core.ui.jar:?]
	at anl.verdi.core.VerdiGUI.isHidden(VerdiGUI.java:255) ~[core.jar:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:412) [core.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:831) [?:?]

I tried to modify the order of the commands as follows, and got the same error.
./verdi.command -f $cwd/data/model/CCTM_combine.2008031.dave.nc.1 -s "O3[1]" -g tile -f $cwd/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[2]" -g tile
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
2021.12.08 15:51:04.621 [main] ERROR anl.verdi.commandline.ScriptHandler - Error in ScriptHandler.dataMap.put 'G'
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.get(int)" because "args" is null
	at anl.verdi.commandline.ScriptHandler$14.run(ScriptHandler.java:542) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1514) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:166) [core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:160) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:178) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:387) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
**Retested using VERDI_2.1.4_linux64_20220526.tar.gz on Atmos, found this issue has resolved.**
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/CCTM_combine.2008031.dave.nc.1 -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile -s "O3[1]-O3[2]" -g tile
Tile plots for three variables were displayed in VERDI window as below:
![issue_203_VERDI_testing_1](https://user-images.githubusercontent.com/73186639/171489560-b76a1dd0-8484-4ad2-a55c-346a5aa19d43.png)

**Comment by cbroker1** [comment]
Retested with `VERDI_2.1.4_win64_20220526.zip` on Windows 11. 

Produced same plot as @yadongxuEPA but produced error in terminal (see img below)

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/43118284/171660988-a6bb86db-bec4-4412-bde7-f023ddc8b693.png">

**Comment by cbroker1** [comment]
Retested using VERDI_2.1.4_win64_20220526.zip on Win 11, found issues has resolved. 

CMD, used:
./run.bat -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/CCTM_combine.2008031.dave.nc.1 -f /work/MOD3APP/yxu/VERDI_2.1.4/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile -s "O3[1]-O3[2]" -g tile

Same tile plot as above displayed.

**Comment by lizadams** [comment]
Confirmed that this also is fixed for the Mac version.

Note: the $cwd command only works in cshell. 
I usually invoke cshell by using

```
csh
```
Then invoke the verdi command

```
./verdi.command -f $cwd/data/model/CCTM_combine.2008031.dave.nc.1 -f $cwd/data/model/CCTM_combine.2008031.dave.nc.2 -s "O3[1]" -g tile -s "O3[2]" -g tile -s "O3[1]-O3[2]" -g tile
```

It generated the three plots as shown above (one plot for each tab in the VERDI window).

There was also a message in the console:

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
