### ISSUE TITLE
Exception in FastTilePlot.updateColorMap

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#204]
This is for the following version
VERDI_2.0_beta_linux64_20190423.tar.gz

I will also test with the newer release..

Using the following command to load a configuration file and create a plot
```
./verdi.sh -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -configFile ~/config_verdi.txt -gtype tile -saveImage "png" $cwd/CCTM46.O3MAX.2nd.png -quit
```
gives the following error:
2019.06.10 12:44:08.191 [main] ERROR anl.verdi.plot.gui.FastTilePlot - Exception in FastTilePlot.updateColorMap
java.lang.NullPointerException
	at gov.epa.emvl.TilePlot.calculateColorIndices(TilePlot.java:1154) ~[core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot.updateColorMap(FastTilePlot.java:2708) [core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot.configure(FastTilePlot.java:2665) [core.jar!/:?]
	at anl.verdi.commandline.ScriptHandler$15.run(ScriptHandler.java:649) [core.jar!/:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1474) [core.jar!/:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:159) [core.jar!/:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:158) [core.jar!/:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:99) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at saf.core.runtime.Boot.run(Boot.java:160) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:333) [saf.core.runtime.jar:?]

I am attaching the config file that was saved using this version of VERDI.
NOTE: there are errors when you try to use a config file between the different versions of VERDI: VERDI_1.5.0 and VERDI_2.0_beta

[config_verdi.txt](https://github.com/CEMPD/VERDI/files/3272963/config_verdi.txt

I've also gotten the following error
./verdi.sh -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -configFile ~/config.verdi -gtype tile -saveImage "png" $cwd/CCTM46.O3MAX.2nd.png -quit
2019.06.10 12:48:46.503 [main] ERROR anl.verdi.commandline.ScriptHandler - IOException in ScriptHandler.dataMap.put 'CONFIGFILE': Error while loading configuration

**Comment by lizadams** [comment]
I am getting the same error with the latest build.
```
 ./verdi.sh -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -configFile $cwd/config_verdi_10.txt -gtype tile -saveImage "png" $cwd/CCTM46.O3MAX.2nd.png -quit
```
2019.06.10 13:41:05.681 [main] ERROR anl.verdi.plot.gui.FastTilePlot - Exception in FastTilePlot.updateColorMap
java.lang.NullPointerException
	at gov.epa.emvl.TilePlot.calculateColorIndices(TilePlot.java:1153) ~[core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot.updateColorMap(FastTilePlot.java:2708) [core.jar!/:?]
	at anl.verdi.plot.gui.FastTilePlot.configure(FastTilePlot.java:2665) [core.jar!/:?]
	at anl.verdi.commandline.ScriptHandler$15.run(ScriptHandler.java:652) [core.jar!/:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1477) [core.jar!/:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:159) [core.jar!/:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:158) [core.jar!/:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:99) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at saf.core.runtime.Boot.run(Boot.java:160) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:333) [saf.core.runtime.jar:?]
```
[lizadams@longleaf-login1 ~/VERDI_2.0_beta]$ ./verdi.sh -version
Version: 2.0_beta 2019-06-10
```

**Comment by lizadams** [comment]
Successfully tested this and confirmed that the exception is no longer generated.
Used the VERDI_2.0_beta_linux64_20190623.tar.gz build.
