### ISSUE TITLE
Error running a batch script from "View Script Editor" in VERDI 2.1 GUI and command line on Linux

### ISSUE THREAD

**Issue by yadongxuEPA** [CEMPD/VERDI#226]
**Describe the bug**
Got an error when running the batch script "file_patterns.txt" in VERDI 2.1 GUI; Got the same error when running it from using command line on Atmos

**To Reproduce**
Steps to reproduce the behavior in VERDI 2.1 GUI:
1. Open VERDI 2.1 GUI
2. Click on "File" from the main menu
3. Scroll down to "View Script Editor" and click
4. In the pop up browser window, go to $cwd/data/scripts to load "file_patterns.txt"
5. click on "run" 
Steps to reproduce the behavior in Linux
1. run this command line "./verdi.sh -batch ./data/scripts/file_patterns.txt “ on Atmos

**Screenshots**

![ch17_batch_script_file_patterns_error](https://user-images.githubusercontent.com/73186639/110003044-013b8e00-7ce4-11eb-9105-6ccd483e5267.png)
![ch17_batch_script_file_patterns_command_line](https://user-images.githubusercontent.com/73186639/110003338-452e9300-7ce4-11eb-8cc6-418d7c73a081.png)

**Context"
Liz did more testing by using the older VERDI versions. Found that the batch script did not work but returned with different error messages.

1) tested with "VERDI_2.0_beta_linux64_20190408.tar.gz"
using command line " ./verdi.sh -batch ./data/scripts/file_patterns.txt"
_2021.03.03 15:02:33.445 [main] ERROR anl.verdi.commandline.task.TilePlotTask - Exception in TilePlotTask.save: null
2021.03.03 15:02:34.935 [Thread-5] ERROR anl.verdi.plot.gui.FastTilePlot - Error rendering FastTilePlot
java.lang.NullPointerException
at anl.verdi.plot.gui.FastTilePlot.resetMenuItems(FastTilePlot.java:2308) ~[core.jar!/:?]
at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:675) [core.jar!/:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]_

2) tested with "VERDI_2.0_linux64_20201019.tar.gz"
using command line "./verdi.sh -batch ./data/scripts/file_patterns.txt "
_Projecting Department_of_State_Valid_QGIS.shp
Projecting states_us_mexico.shp
Projecting cb_2014_us_state_500k.shp
2021.03.03 15:05:14.516 [main] ERROR anl.verdi.commandline.task.TilePlotTask - Exception in TilePlotTask.save: null
Projecting cb_2014_us_county_500k.shp
2021.03.03 15:05:14.795 [Thread-5] ERROR anl.verdi.plot.gui.FastTilePlot - Error rendering FastTilePlot
java.lang.NullPointerException
at anl.verdi.plot.gui.FastTilePlot.resetMenuItems(FastTilePlot.java:2315) ~[core.jar!/:?]
at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:676) [core.jar!/:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Projecting huc250k.shp
Projecting ne_10m_rivers_lake_centerlines.shp
Projecting tl_2015_us_primaryroads.shp_

It is very likely that we had been having this issue of running batch script in VERDI even in the older versions.

**Comment by lizadams** [comment]
Using VERDI_2.0_mac_20210327.tar.gz
I am getting the following warnings:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/proj/ie/proj/CMAS/VERDI/VERDI_2.0/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

The script appeared to run, and gave the following pop-up.
<img width="856" alt="Screen Shot 2021-03-30 at 5 10 18 PM" src="https://user-images.githubusercontent.com/1183863/113057282-d7f30e00-917a-11eb-84cb-ee513abae367.png">

The performance seems slow on the mac and Linux, and the run command on Windows seemed to make VERDI hang, and it did not create a plot.

In addition, on Windows, the View Script Editor, doesn't open to the location where the scripts are.
It looks in Documents> instead of in VERDI > data > scripts
I tried editing the config.properties file in my home directory on the windows machine, but this didn't solve the issue

The only plot that was created was:
O3_tile.jpeg

In the past, the Global section of the file_patterns.txt would also create plots.

**Comment by lizadams** [comment]
I also obtained this error when trying to run file_patterns.txt in the VERDI Batch Script editor.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/C:/Users/lizadams/Downloads/VERDI_2.0_win64_20210327/VERDI_2.0_win/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 30, 2021 9:55:49 PM org.geotools.resources.NIOUtilities log
SEVERE: Error attempting to close a mapped byte buffer : java.nio.DirectByteBuffer
 JVM : 15.0.1 Oracle Corporation
java.lang.IllegalAccessException: class org.geotools.resources.NIOUtilities$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @1422ac7f
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:693)
        at java.base/java.lang.reflect.Method.invoke(Method.java:556)
        at org.geotools.resources.NIOUtilities$1.run(NIOUtilities.java:218)
        at org.geotools.resources.NIOUtilities$1.run(NIOUtilities.java:206)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.geotools.resources.NIOUtilities.clean(NIOUtilities.java:205)
        at org.geotools.data.PrjFileReader.close(PrjFileReader.java:161)
        at org.geotools.data.PrjFileReader.<init>(PrjFileReader.java:90)
        at org.geotools.data.PrjFileReader.<init>(PrjFileReader.java:62)
        at org.geotools.data.shapefile.ShapefileSetManager.openPrjReader(ShapefileSetManager.java:101)
        at org.geotools.data.shapefile.ShapefileFeatureSource.readAttributes(ShapefileFeatureSource.java:523)
        at org.geotools.data.shapefile.ShapefileFeatureSource.buildFeatureType(ShapefileFeatureSource.java:479)
        at org.geotools.data.shapefile.ShapefileFeatureStore.buildFeatureType(ShapefileFeatureStore.java:137)
        at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:328)
        at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:297)
        at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:106)
        at anl.verdi.plot.gui.VerdiStyle.getStyleFromPgm(VerdiStyle.java:333)
        at anl.verdi.plot.gui.VerdiStyle.createVerdiStyle(VerdiStyle.java:251)
        at anl.verdi.plot.gui.VerdiStyle.calcVerdiStyle(VerdiStyle.java:130)
        at anl.verdi.plot.gui.VerdiStyle.<init>(VerdiStyle.java:96)
        at anl.verdi.plot.gui.VerdiBoundaries.setFileName(VerdiBoundaries.java:93)
        at gov.epa.emvl.Mapper.getWorldMap(Mapper.java:455)
        at gov.epa.emvl.Mapper.cacheMaps(Mapper.java:71)
        at gov.epa.emvl.Mapper.<init>(Mapper.java:90)
        at anl.verdi.plot.gui.FastTilePlot.<init>(FastTilePlot.java:1573)
        at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:142)
        at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:146)
        at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:98)
        at anl.verdi.gui.ScriptPanel.processScript(ScriptPanel.java:275)
        at anl.verdi.gui.ScriptPanel.access$12(ScriptPanel.java:270)
        at anl.verdi.gui.ScriptPanel$4.actionPerformed(ScriptPanel.java:207)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by lizadams** [comment]
When looking at the file datestamps in File Explorer in Windows, the date stamps are not correct.
I used Git Bash to look at the date stamps in the files under
VERDI_2.0_win64_20210327/VERDI_2.0_win/data/plots
I can now see that the O3_tile.jpeg file was created.
Note, it is still cutting off the Color Bar legend on the right hand side.

**Comment by lizadams** [comment]
Getting 
Exception in thread "pool-3-thread-1" java.lang.OutOfMemoryError: Java heap space

**Comment by lizadams** [comment]
It looks like we may need to upgrade to JDK 16.
https://bugs.openjdk.java.net/browse/JDK-8188055

**Comment by lizadams** [comment]
Increased the maximum heap space to -Xmx8192 and got more information
'#set' is not recognized as an internal or external command,
operable program or batch file.
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/C:/Users/lizadams/Downloads/VERDI_2.0_win64_20210327/VERDI_2.0_win/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 31, 2021 12:09:44 AM org.geotools.resources.NIOUtilities log
SEVERE: Error attempting to close a mapped byte buffer : java.nio.DirectByteBuffer
 JVM : 16 Oracle Corporation
java.lang.IllegalAccessException: class org.geotools.resources.NIOUtilities$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @1bc49bc5
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:687)
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
        at org.geotools.resources.NIOUtilities$1.run(NIOUtilities.java:218)
        at org.geotools.resources.NIOUtilities$1.run(NIOUtilities.java:206)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.geotools.resources.NIOUtilities.clean(NIOUtilities.java:205)
        at org.geotools.data.PrjFileReader.close(PrjFileReader.java:161)
        at org.geotools.data.PrjFileReader.<init>(PrjFileReader.java:90)
        at org.geotools.data.PrjFileReader.<init>(PrjFileReader.java:62)
        at org.geotools.data.shapefile.ShapefileSetManager.openPrjReader(ShapefileSetManager.java:101)
        at org.geotools.data.shapefile.ShapefileFeatureSource.readAttributes(ShapefileFeatureSource.java:523)
        at org.geotools.data.shapefile.ShapefileFeatureSource.buildFeatureType(ShapefileFeatureSource.java:479)
        at org.geotools.data.shapefile.ShapefileFeatureStore.buildFeatureType(ShapefileFeatureStore.java:137)
        at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:328)
        at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:297)
        at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:106)
        at anl.verdi.plot.gui.VerdiStyle.getStyleFromPgm(VerdiStyle.java:333)
        at anl.verdi.plot.gui.VerdiStyle.createVerdiStyle(VerdiStyle.java:251)
        at anl.verdi.plot.gui.VerdiStyle.calcVerdiStyle(VerdiStyle.java:130)
        at anl.verdi.plot.gui.VerdiStyle.<init>(VerdiStyle.java:96)
        at anl.verdi.plot.gui.VerdiBoundaries.setFileName(VerdiBoundaries.java:93)
        at gov.epa.emvl.Mapper.getWorldMap(Mapper.java:455)
        at gov.epa.emvl.Mapper.cacheMaps(Mapper.java:71)
        at gov.epa.emvl.Mapper.<init>(Mapper.java:90)
        at anl.verdi.plot.gui.FastTilePlot.<init>(FastTilePlot.java:1573)
        at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:142)
        at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:146)
        at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:98)
        at anl.verdi.gui.ScriptPanel.processScript(ScriptPanel.java:275)
        at anl.verdi.gui.ScriptPanel.access$12(ScriptPanel.java:270)
        at anl.verdi.gui.ScriptPanel$4.actionPerformed(ScriptPanel.java:207)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Exception in thread "TimerQueue" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.locks.ReentrantLock$Sync.newCondition(ReentrantLock.java:190)
        at java.base/java.util.concurrent.locks.ReentrantLock.newCondition(ReentrantLock.java:537)
        at java.desktop/javax.swing.TimerQueue.run(TimerQueue.java:194)
        at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.OutOfMemoryError: Java heap space
java.lang.NullPointerException: Cannot invoke "org.geotools.data.simple.SimpleFeatureSource.getFeatures()" because "sourceShapefile" is null
        at anl.verdi.plot.gui.VerdiShapefileUtil.projectShapefile(VerdiShapefileUtil.java:313)
        at anl.verdi.plot.gui.VerdiShapefileUtil.projectShapefile(VerdiShapefileUtil.java:276)
        at anl.verdi.plot.gui.VerdiStyle.projectShapefile(VerdiStyle.java:193)
        at anl.verdi.plot.gui.VerdiStyle.call(VerdiStyle.java:166)
        at anl.verdi.plot.gui.VerdiStyle.call(VerdiStyle.java:1)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by lizadams** [comment]
Looking in the following code:
https://github.com/CEMPD/VERDI/blob/c5d06a1d933e4e2d727fc98946c575416e17310c/verdi_core/src/anl/verdi/plot/gui/VerdiShapefileUtil.java

Iine 135
		String vFileName = "/home/verdi/verdi-shapefile/VERDI/verdi_bootstrap/data/map_state/cb_2014_us_state_500k.shp";

Is it correct to use a hard coded path? 
This file does exist in the VERDI tar.gz file:
VERDI_2.0/plugins/bootstrap/data/map_state/cb_2014_us_state_500k.shp

**Comment by systemsgo** [comment]
> Looking in the following code:
> https://github.com/CEMPD/VERDI/blob/c5d06a1d933e4e2d727fc98946c575416e17310c/verdi_core/src/anl/verdi/plot/gui/VerdiShapefileUtil.java
> 
> Iine 135
> String vFileName = "/home/verdi/verdi-shapefile/VERDI/verdi_bootstrap/data/map_state/cb_2014_us_state_500k.shp";
> 
> Is it correct to use a hard coded path?
> This file does exist in the VERDI tar.gz file:
> VERDI_2.0/plugins/bootstrap/data/map_state/cb_2014_us_state_500k.shp

This was leftover debug code, but I've cleaned up the local reference.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210405.tar.gz, VERDI_2.0_win64_20210405.tar.gz in two ways: interactively in VERDI 2.1 GUI and by running command line "./verdi.sh -batch ./data/scripts/file_patterns.txt “ on Atmos.  Got the same results:

1) the script did ran through and the tile plot was created
![Issue_226_VERDI_testing_04052021_1](https://user-images.githubusercontent.com/73186639/114470298-a63b6780-9bbc-11eb-8bfb-cf09c414dbcf.png)
2) we still have the issue of the legend label on the right got cut-off
![Issue_226_VERDI_testing_04052021_2](https://user-images.githubusercontent.com/73186639/114470359-c0754580-9bbc-11eb-8406-bfa623e5ed61.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz in two ways: interactively in VERDI 2.1 GUI and by running command line "./verdi.sh -batch ./data/scripts/file_patterns.txt “ on Atmos. Found that the issue in the previous build as described above still persists. 
![Issue_226_VERDI_testing_04272021](https://user-images.githubusercontent.com/73186639/116594986-d25f2400-a8f0-11eb-8e77-d4da15aa02b4.png)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz in two ways: interactively in VERDI 2.1 GUI and by running command line "./verdi.sh -batch ./data/scripts/file_patterns.txt “ on Atmos. Found that the issue has resolved.
![issue_226_VERDI_testing_20210526](https://user-images.githubusercontent.com/73186639/119857479-99ab6e00-bee1-11eb-956c-7674722a2bc6.jpg)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210906.tar.gz in two ways: interactively in VERDI 2.1 GUI and by running command line "./verdi.sh -batch ./data/scripts/file_patterns.txt “ on Atmos. **The batch script worked properly and the upgraded openJDK has not caused any problem in this issue.**   
![issue_226_VERDI_testing_1_20210906](https://user-images.githubusercontent.com/73186639/132408162-57aa55ce-1f7c-4175-85a4-7cd7d3f6ba02.jpg)
