### ISSUE TITLE
Unwanted text added to the plot title of "Vertical Cross Section Plot" when use the spin controller to change the time step

### ISSUE THREAD

**Issue by yadongxuEPA** [CEMPD/VERDI#227]
**Describe the bug**
When creating a "Vertical Cross Section Plot" in VERDI 2.1 GUI ( VERDI_2.0_linux64_20210222.tar.gz; VERDI_2.0_win64_20210222.tar.gz, VERDI_2.0_mac_20210222.tar.gz) and using the spin controller to change the time step, every click on the spin controller added an unwanted ".0" to the title. 

**To Reproduce**
1. Open VERDI 2.1 GUI
2. Add this dataset "CCTM46_P16.base02a.36k.O3MAX" and create a formula "O3[1]"
3. Click on "Vertical Cross Section Plot"
4. Select Y-Axis Cross Section, Row 1
4. Click on the spin controller next to the "Time Step" to change the time step
5. See error in the plot title 

**Screenshots**
![ch10_vertical_cross_section_plot_title](https://user-images.githubusercontent.com/73186639/110006497-bcb1f180-7ce7-11eb-95dd-c4d5221e9cc6.png)

**Additional context**
Tested this issue on Windows, Mac and Linux, got the same behavior.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210311.tar.gz; VERDI_2.0_win64_20210311.tar.gz.
The issue is resolved.  No more unwanted text appeared in the title of "Vertical Cross Section Plot"

![Screenshot_issue227_retest_03112021](https://user-images.githubusercontent.com/73186639/111205432-9d477e00-859d-11eb-8768-65de22420382.png)

**Comment by lizadams** [comment]
I've tested this interactively, and the title no longer grows, and the spinner controls work.
But- VERDI is throwing errors.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.util.GregorianCalendar.getTime()" because "date" is null
	at anl.verdi.util.Utilities.formatShortDate(Utilities.java:47)
	at anl.verdi.plot.gui.TimeConstantAxisPanel$SpinnerListener.stateChanged(TimeConstantAxisPanel.java:44)
	at java.desktop/javax.swing.JSpinner.fireStateChanged(JSpinner.java:461)
	at java.desktop/javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:388)
	at java.desktop/javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:120)
	at java.desktop/javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:460)
	at java.desktop/javax.swing.JSpinner.setValue(JSpinner.java:355)
	at java.desktop/com.apple.laf.AquaSpinnerUI$ArrowButtonHandler.actionPerformed(AquaSpinnerUI.java:387)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)

**Comment by lizadams** [comment]
I also tried to create this plot this using a command line script, but it isn't working:
According to our help instructions
./verdi.sh -help
The command should be:
-verticalCrossPlot X|Y <column/row>

I tried the following:
./verdi.command -f $cwd/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1

Getting the following error:

2021.03.31 10:57:36.331 [main] ERROR anl.verdi.commandline.ScriptHandler - Error in ScriptHandler.dataMap.put 'VERTICALCROSSPLOT'
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "anl.verdi.plot.config.VertCrossPlotConfiguration.getDisplayMode()" is null
	at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:116) ~[core.jar:?]
	at anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot(PlotFactory.java:133) ~[core.jar:?]
	at anl.verdi.plot.gui.VerticalCrossPlotCreator.createVertPlot(VerticalCrossPlotCreator.java:128) ~[core.jar:?]
	at anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(VerticalCrossPlotCreator.java:97) ~[core.jar:?]
	at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler$45.run(ScriptHandler.java:1397) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1477) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:159) [core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:160) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:160) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:334) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
I tried to retest this issue with VERDI_2.0_linux64_20210408.tar.gz by using a command line script:
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.0/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1

Got the following error messages:
2021.04.15 13:01:52.461 [main] ERROR anl.verdi.commandline.ScriptHandler - Error in ScriptHandler.dataMap.put 'VERTICALCROSSPLOT'
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionSliceSize()" is null
        at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:116) ~[core.jar:?]
        at anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot(PlotFactory.java:133) ~[core.jar:?]
        at anl.verdi.plot.gui.VerticalCrossPlotCreator.createVertPlot(VerticalCrossPlotCreator.java:128) ~[core.jar:?]
        at anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(VerticalCrossPlotCreator.java:97) ~[core.jar:?]
        at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39) ~[core.jar:?]
        at anl.verdi.commandline.ScriptHandler$45.run(ScriptHandler.java:1425) [core.jar:?]
        at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1505) [core.jar:?]
        at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:166) [core.jar:?]
        at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:160) [core.jar:?]
        at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
        at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at saf.core.runtime.Boot.run(Boot.java:161) [saf.core.runtime.jar:?]
        at saf.core.runtime.Boot.main(Boot.java:354) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
Retested this issue with VERDI_2.0_linux64_20210427.tar.gz by using a command line script:
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.0/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1

Got the same error messages as the previous build.

[yxu01@atmos1 VERDI_2.0]$ ./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.0/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1

2021.04.29 13:21:01.237 [main] ERROR anl.verdi.commandline.ScriptHandler - Error in ScriptHandler.dataMap.put 'VERTICALCROSSPLOT'
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "anl.verdi.plot.config.VertCrossPlotConfiguration.getCrossSectionSliceSize()" is null
        at anl.verdi.plot.types.VerticalCrossSectionPlot.<init>(VerticalCrossSectionPlot.java:116) ~[core.jar:?]
        at anl.verdi.plot.gui.PlotFactory.getVerticalCrossPlot(PlotFactory.java:133) ~[core.jar:?]
        at anl.verdi.plot.gui.VerticalCrossPlotCreator.createVertPlot(VerticalCrossPlotCreator.java:128) ~[core.jar:?]
        at anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(VerticalCrossPlotCreator.java:97) ~[core.jar:?]
        at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39) ~[core.jar:?]
        at anl.verdi.commandline.ScriptHandler$45.run(ScriptHandler.java:1425) [core.jar:?]
        at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1505) [core.jar:?]
        at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:166) [core.jar:?]
        at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:160) [core.jar:?]
        at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
        at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at saf.core.runtime.Boot.run(Boot.java:161) [saf.core.runtime.jar:?]
        at saf.core.runtime.Boot.main(Boot.java:354) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
Retested this issue with VERDI_2.1_linux64_20210526.tar.gz by using a command line script:
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1
No error poped-up and the VERDI plot was brought up.  But somehow the above command line generated a vertical cross plot for Row 2 at time step 2 instead of Row 1 at time step 1. Please review.
![issue_227_VERDI_testing_20210526](https://user-images.githubusercontent.com/73186639/119861689-ac27a680-bee5-11eb-9bfc-e2ffbc5d37d2.jpg)

**Comment by yadongxuEPA** [comment]
Retested this issue with VERDI_2.1_linux64_20210707.tar.gz by using a command line script:
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1
The above command line generated a vertical cross plot for Row 1 at time step 2 instead of Row 1 at time step 1. There was inconsistency between the time step on the top and the one in the x-axis label.  Please review.  
![issue_227_VERDI_testing_1_07072021_edited](https://user-images.githubusercontent.com/73186639/124961539-9ed50000-dfeb-11eb-9ebf-03057e0383df.jpg)

**Comment by yadongxuEPA** [comment]
Retested this issue with VERDI_2.1_linux64_20210809.tar.gz by using a command line script:
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1
The above command line generated a vertical cross plot for Row 1 at time step 2,  the time step on the top and the one in the x-axis label was consistent. 
![issue_227_VERDI_testing_3_20210809](https://user-images.githubusercontent.com/73186639/128927487-33ab326a-08f3-4a20-a2bd-90473f82fab1.jpg)
**However, when I continued to use the "Row" spinner, the time step on the top started to change, the inconsistency between the time step on the top and the one in the x-axis label appeared again.** 
![issue_227_VERDI_testing_1_and_2_edited_20210809](https://user-images.githubusercontent.com/73186639/128927941-9e692573-f001-48cf-9a91-0f32a881ab34.jpg)

**Comment by yadongxuEPA** [comment]
Retested this issue with VERDI_2.1_linux64_20210906.tar.gz (also tested with VERDI_2.1_win64_20210906.zip)  by using a command line script:
./verdi.sh -f /work/MOD3APP/yxu/VERDI_2.1/data/model/CCTM46_P16.baseO2a.36k.O3MAX -s "O3[1]" -verticalCrossPlot Y 1
The above command line generated a vertical cross plot for Row 1 at time step 1, the time step on the top and the one in the x-axis label was consistent.
![issue_227_VERDI_testing_1_20210906](https://user-images.githubusercontent.com/73186639/132383545-92c3d6f8-e97b-4e00-9216-1b6c8b6af78d.jpg)
**The "Row" and "Time Steps" spinners also worked properly.  The issue has resolved.**
![issue_227_VERDI_testing_2_20210906](https://user-images.githubusercontent.com/73186639/132383728-314d6dd2-81cd-48be-9193-3d65cc8d359a.jpg)
