### ISSUE TITLE
VERDI hanging when exporting shapefile

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#233]
**Describe the bug**
VERDI on windows, loaded in geo_em.d03.nc and exported as shapefile starts using > 99% of CPU and hangs.

**To Reproduce**
1. Go to https://drive.google.com/drive/u/1/folders/10AypuLoizaGRGLmJnIe2cy83sS3FaKUj
2. Download geo_em.d03.nc
3. Load file into verdi and export as shapefile.
4. See error:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/C:/Users/lizadams/Downloads/VERDI_2.0_win64_20210327/VERDI_2.0_win/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 31, 2021 2:44:47 AM org.geotools.resources.NIOUtilities log
SEVERE: Error attempting to close a mapped byte buffer : java.nio.DirectByteBuffer
 JVM : 15.0.1 Oracle Corporation
java.lang.IllegalAccessException: class org.geotools.resources.NIOUtilities$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @277b8fa4
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:693)
        at java.base/java.lang.reflect.Method.invoke(Method.java:556)
        at org.geotools.resources.NIOUtilities$1.run(NIOUtilities.java:218)
        at org.geotools.resources.NIOUtilities$1.run(NIOUtilities.java:206)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.geotools.resources.NIOUtilities.clean(NIOUtilities.java:205)
        at org.geotools.data.PrjFileReader.close(PrjFileReader.java:161)
        at org.geotools.data.PrjFileReader.<init>(PrjFileReader.java:90)
        at org.geotools.data.PrjFileReader.<init>(PrjFileReader.java:62)
        at org.geotools.data.shapefile.ShapefileSetManager.openPrjReader(ShapefileSetManager.java:101)
        at org.geotools.data.shapefile.ShapefileFeatureSource.readAttributes(ShapefileFeatureSource.java:523)
        at org.geotools.data.shapefile.ShapefileFeatureSource.buildFeatureType(ShapefileFeatureSource.java:479)
        at org.geotools.data.shapefile.ShapefileFeatureStore.buildFeatureType(ShapefileFeatureStore.java:137)
        at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:328)
        at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:297)
        at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:106)
        at anl.verdi.plot.gui.VerdiStyle.getStyleFromPgm(VerdiStyle.java:333)
        at anl.verdi.plot.gui.VerdiStyle.createVerdiStyle(VerdiStyle.java:251)
        at anl.verdi.plot.gui.VerdiStyle.calcVerdiStyle(VerdiStyle.java:130)
        at anl.verdi.plot.gui.VerdiStyle.<init>(VerdiStyle.java:96)
        at anl.verdi.plot.gui.VerdiBoundaries.setFileName(VerdiBoundaries.java:93)
        at gov.epa.emvl.Mapper.getWorldMap(Mapper.java:455)
        at gov.epa.emvl.Mapper.cacheMaps(Mapper.java:71)
        at gov.epa.emvl.Mapper.<init>(Mapper.java:90)
        at anl.verdi.plot.gui.FastTilePlot.<init>(FastTilePlot.java:1573)
        at anl.verdi.plot.gui.action.FastTilePlot.actionPerformed(FastTilePlot.java:54)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Exception in thread "Basic L&F File Loading Thread" java.lang.NullPointerException: Cannot read field "value" because "original" is null
        at java.base/java.lang.String.<init>(String.java:254)
        at anl.verdi.plot.util.PlotExporter.findExtension(PlotExporter.java:233)
        at anl.verdi.plot.util.PlotExporter.access$0(PlotExporter.java:224)
        at anl.verdi.plot.util.PlotExporter$ImageFileFilter.accept(PlotExporter.java:66)
        at java.desktop/javax.swing.JFileChooser.accept(JFileChooser.java:1653)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:313)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:289)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Expected behavior**
Expect that VERDI can export gridded data as shapefile.

**Screenshots**
VERDI is using > 99% of CPU and is hanging when I try to perform this.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
It looks like the files were saved to the Documents directory, but they were incomplete.
100 Mar 30 22:49 LANDMASK_geo_em.d03.shx
  100 Mar 30 22:49 LANDMASK_geo_em.d03.shp
 632 Mar 30 22:49 LANDMASK_geo_em.d03.prj
  65 Mar 30 22:49 LANDMASK_geo_em.d03.dbf

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz, VERDI was able to export "geo_em.d03.nc" as shapefiles.

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20210526.tar.gz, VERDI was able to export "geo_em.d03.nc" as shapefiles. The projection string has changed to the followings:
**PROJCS["unknown", GEOGCS["GCS_unknown", DATUM["D_unknown", SPHEROID["unknown", 6370000.0, 0.0]]**, PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Longitude", EAST], AXIS["Latitude", NORTH]], PROJECTION["Lambert_Conformal_Conic"], PARAMETER["central_meridian", -97.0], PARAMETER["latitude_of_origin", 36.77481460571289], PARAMETER["standard_parallel_1", 45.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], PARAMETER["scale_factor", 1.0], PARAMETER["standard_parallel_2", 33.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]
The issue has resolved.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz and VERDI_2.1_win64_20210906.tar.gz, confirmed that the upgraded openJDK has not caused any problem on this issue.**
