### ISSUE TITLE
Vector Overlay Script error

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#235]
**Describe the bug**
The bug appears for the following batch scripts:
multifiles.txt
TA_drawgridlines.txt
vector_overlay.txt

**To Reproduce**
1. VERDI > File > View Script Editor > select batch file
2. Click on Run
3. Obtain an error "Cannot invoke java.util.collection.toArray() because "c" is null

Solution is to fix the scripts.

Change
dir=../verdi_dist/distfiles/data/model
to
 dir=../../data/model

Change
imageDir=../verdi_dist/distfiles/data/plots
to
imageDir=../../data/plots

Adding this fix to the pull request.

**Comment by lizadams** [comment]
The plot that is created by the batch script for the TA_drawgridlines.txt script has the incorrect legend label.
Compare
![METCRO3D_TA_ts3](https://user-images.githubusercontent.com/1183863/113091661-689d0e80-91ba-11eb-83fe-8ded4d6d75ec.png)

To what was generated by previous release of VERDI
![METCRO3D_TA_ts3](https://user-images.githubusercontent.com/1183863/113091708-7eaacf00-91ba-11eb-9601-f17ae1a4af3e.png)

**Comment by lizadams** [comment]
The vector overlay script doesn't generate any output.
vector_overlay.txt

The following error message is created:
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "java.util.Map.get(Object)" is null
	at anl.verdi.commandline.task.TilePlotTask.createFormula(TilePlotTask.java:373)
	at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:134)
	at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:146)
	at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:98)
	at anl.verdi.gui.ScriptPanel.processScript(ScriptPanel.java:275)
	at anl.verdi.gui.ScriptPanel.access$12(ScriptPanel.java:270)
	at anl.verdi.gui.ScriptPanel$4.actionPerformed(ScriptPanel.java:207)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at anl.verdi.gui.ScriptPanel$4.actionPerformed(ScriptPanel.java:197)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by lizadams** [comment]
Using the command line option I get a similar error:
./verdi.command -batch data/scripts/vector_overlay.txt
2021.03.31 00:58:50.596 [main] ERROR anl.verdi.commandline.task.TilePlotTask - Null Pointer Exception in TilePlotTask.createFormula: Cannot invoke "String.trim()" because the return value of "java.util.Map.get(Object)" is null
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "java.util.Map.get(Object)" is null
	at anl.verdi.commandline.task.TilePlotTask.createFormula(TilePlotTask.java:373)
	at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:134)
	at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:146)
	at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:125)
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:142)
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93)
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at saf.core.runtime.Boot.run(Boot.java:160)
	at saf.core.runtime.Boot.main(Boot.java:334)

**Comment by lizadams** [comment]
Using the command line option for the following script, I get an error, but the file is saved
./verdi.command -batch data/scripts/TA_drawgridlines.txt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/Applications/VERDI_2.0/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021.03.31 01:02:49.721 [main] ERROR anl.verdi.commandline.task.TilePlotTask - Exception in TilePlotTask.save: null
(base) liz-mbp:VERDI_2.0 lizadams$ ls -rlt data/plots
total 904
-rw-r--r--@ 1 lizadams  admin  57363 Mar 31 00:21 CCTM46_P16.baseO2a.36k.O3MAX_tile.png
-rw-r--r--  1 lizadams  admin  51146 Mar 31 01:01 CCTM_combine.2008031.dave.nc.1_tile.jpeg
-rw-r--r--  1 lizadams  admin  51146 Mar 31 01:01 CCTM_combine.2008031.dave.nc.3_tile.jpeg
-rw-r--r--  1 lizadams  admin  51146 Mar 31 01:01 CCTM_combine.2008031.dave.nc.2_tile.jpeg
-rw-r--r--  1 lizadams  admin  47355 Mar 31 01:01 GRIDCRO2D_mercator_tile.jpeg
-rw-r--r--  1 lizadams  admin  33021 Mar 31 01:01 Double_36k.O3.png
-rw-r--r--  1 lizadams  admin  39682 Mar 31 01:01 Zero_out_36k.O3.jpeg
-rw-r--r--  1 lizadams  admin  42820 Mar 31 01:01 three_components_36k.O3.jpeg
-rw-r--r--  1 lizadams  admin  21953 Mar 31 01:01 quaduple_36k.O3.jpeg
**-rw-r--r--  1 lizadams  admin  42115 Mar 31 01:02 METCRO3D_TA_ts3.png**

**Comment by lizadams** [comment]
I can't create the equivalent vector overlay plot with a command line script, but I can load all the variables and create the tile plot using this script, and then interactively create the vector overlay.
When I do this, I get the following:

./verdi.command -f $cwd/data/model/CCTM47_aac_spr06.12k.CONC.2006113.O3.ncf -s "O3[1]" -g tile -f $cwd/data/model/metdot3d_12k.uwind.vwind -s "UWIND[2]" -s "VWIND[2]" 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.resources.NIOUtilities (file:/Applications/VERDI_2.0/plugins/core/lib/geo-19/gt-metadata-19.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.geotools.resources.NIOUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021.03.31 11:29:54.321 [Thread-3] ERROR anl.verdi.plot.gui.FastTilePlot - FastTilePlot's run method
java.lang.ArithmeticException: / by zero
	at gov.epa.emvl.TilePlot.drawAxis(TilePlot.java:353) ~[core.jar:?]
	at gov.epa.emvl.TilePlot.draw(TilePlot.java:190) ~[core.jar:?]
	at anl.verdi.plot.gui.FastTilePlot$5.run(FastTilePlot.java:642) [core.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by systemsgo** [comment]
> Using the command line option I get a similar error:
> ./verdi.command -batch data/scripts/vector_overlay.txt
> 2021.03.31 00:58:50.596 [main] ERROR anl.verdi.commandline.task.TilePlotTask - Null Pointer Exception in TilePlotTask.createFormula: Cannot invoke "String.trim()" because the return value of "java.util.Map.get(Object)" is null
> java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "java.util.Map.get(Object)" is null
> at anl.verdi.commandline.task.TilePlotTask.createFormula(TilePlotTask.java:373)
> at anl.verdi.commandline.task.TilePlotTask.run(TilePlotTask.java:134)
> at anl.verdi.commandline.BatchScriptHandler.processTasks(BatchScriptHandler.java:146)
> at anl.verdi.commandline.BatchScriptHandler.run(BatchScriptHandler.java:125)
> at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:142)
> at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93)
> at saf.core.runtime.CorePlugin.run(CorePlugin.java:48)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> at saf.core.runtime.Boot.run(Boot.java:160)
> at saf.core.runtime.Boot.main(Boot.java:334)

What variable is this script meant to display?  I'm not sure what it's trying to do.

**Comment by lizadams** [comment]
The script is split into a Global Task which applies to all subtasks unless the subtask overwrites a setting.
<Global>
                configFile=../../data/configs/o3_10bin.cfg
                dir=../../data/model
                saveImage=jpeg
                imageDir=../../data/plots
                </Global>

The above global task sets the configuration file
Sets the data directory.
Sets the image save format
Sets the image directory

                ###########################
                # Vector tests            #
                ###########################

                <Task>
                gtype=tile
                f=CCTM47_aac_spr06.12k.CONC.2006113.O3.ncf
                f=metdot3d_12k.uwind.vwind
                vectorTile=O3[1],UWIND[2],VWIND[2]
                titleString="Ozone with wind vector overlay (UWINDxVWIND)"
                imageFile=vector-tile-test
                </Task>

The above Vector Test 
sets the type of plot to be a tile plot
sets the first file to be loaded as the gridded data containing the variable O3
sets the second file to be loaded as the gridded data containing the uwind and vwind variables
Create a vector overlay tile plot, using O3[1] as the base variable, and UWIND[2] and VWIND[2] as the vector overlay.
Similar to what you can do interactively
Then the title string is defined
The image file name is defined.

When you run the batch script, you should see a plot created with the following path and name:
../../data/plots/vector-tile-test.jpeg

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.0_linux64_20210427.tar.gz in two methods: in GUI and using command line.  Found that the issue is partially solved.  
1) The batch scripts "TA_drawgridlines.txt" and "vector_overlay.txt" worked.  
![Issue_235_VERDI_testing_04272021_1](https://user-images.githubusercontent.com/73186639/117077416-104fb400-ad06-11eb-9d66-5022f26050ca.png)
![Issue_235_VERDI_testing_04272021_3](https://user-images.githubusercontent.com/73186639/117077474-2e1d1900-ad06-11eb-8813-6ff570391ff3.png)
![Issue_235_VERDI_testing_04272021_2](https://user-images.githubusercontent.com/73186639/117078024-1e520480-ad07-11eb-9989-b72eccbe8133.png)
Noticing the plot title overflowed. 
2) The batch script "multifiles.txt" did run successfully. But the color map legend on the right got cut off a bit. 
![Issue_235_VERDI_testing_04272021_4](https://user-images.githubusercontent.com/73186639/117078261-8dc7f400-ad07-11eb-862c-cb05edb6fd4e.png)
![Issue_235_VERDI_testing_04272021_6](https://user-images.githubusercontent.com/73186639/117078276-94566b80-ad07-11eb-8891-5bdd577bfcc3.png)

**Comment by systemsgo** [comment]
The title font can be specified using the anl.verdi.plot.config.PlotConfiguration.title_font key in a config file.  Thee easiest way to do this is to configure a plot using the UI, then save the plot config and reference it using the script / command line's configFile parameter.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1_linux64_20210906.tar.gz and VERDI_2.1_win64_20210906.zip, confirmed that the upgraded openJDK has not caused any problem on this issue.**
