### ISSUE TITLE
MPAS scatterplot tool does not work

### ISSUE THREAD

**Issue by cwsimmon** [CEMPD/VERDI#255]
Reported by Russ Bullock

The scatterplot tool does not work for MPAS model data.  While the tool does open a window to obtain user input for the formulas to be used for the domain and range of the plot, hitting the OK button to accept those choices results in no action other than a constant dotted box highlighting the scatter plot tool option.  The following error is written to the command prompt window:

_Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "anl.verdi.data.CoordAxis.getRange()" because the return value of "anl.verdi.data.Axes.getCellAxis()" is null_

**Comment by yadongxuEPA** [comment]
**To Reproduce**
Steps to reproduce the behavior:

1) Load the 2-meter temperature data file "t2m_only.2016-07-04.nc" into verdi and create two variables:" t2m[1]" and "2*t2m[1]".
2) On the top menu bar, click on "Scatter Plot", in the pop-up window, assign "t2m[1]" to X-Axis and "2*t2m[1]" to Y_Axis, then click "OK".

**Expected behavior**
A scatter plot showing the relationship between the above two variables should be correctly displayed.  

**Tested with VERDI_2.1_linux64_20210707.tar.gz and VERDI_2.1_win64_20210707.zip and found that the scatter plot was actually displayed correctly** (Shown as below).
![issue_255_VERDI_testing_1_07072021](https://user-images.githubusercontent.com/73186639/125990523-5fb2cef7-ecc1-4a1b-a07c-f9651e6e07a7.jpg)

**However, the following error messages were written to the command prompt window:**
ucar.ma2.InvalidRangeException: Bad ranges [] length
        at ucar.ma2.Index.section(Index.java:243)
        at ucar.ma2.Array.section(Array.java:600)
        at anl.verdi.data.DataUtilities.minMax(DataUtilities.java:370)
        at anl.verdi.plot.types.ScatterPlot.updateTimeStepLayer(ScatterPlot.java:351)
        at anl.verdi.plot.types.ScatterPlot$1.stateChanged(ScatterPlot.java:216)
        at java.desktop/javax.swing.JSpinner.fireStateChanged(JSpinner.java:461)
        at java.desktop/javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:388)
        at java.desktop/javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:120)
        at java.desktop/javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:460)
        at java.desktop/javax.swing.JSpinner.setValue(JSpinner.java:355)
        at java.desktop/javax.swing.plaf.basic.BasicSpinnerUI$ArrowButtonHandler.actionPerformed(BasicSpinnerUI.java:668)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by yadongxuEPA** [comment]
Retested with VERDI_2.1_linux64_20211103.tar.gz on Atmos, the same error messages persist  when I tried to change the time steps.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.4_linux64_20220706.tar.gz on Atmos, found that this issue has not resolved.**
Steps to reproduce the behavior:
1.Load the 2-meter temperature data file "t2m_only.2016-07-04.nc" into verdi and create two formulas:" t2m[1]" and "2*t2m[1]".
2.On the top menu bar, click on "Scatter Plot".
3. In the pop-up window, assign "t2m[1]" to X-Axis and "2*t2m[1]" to Y_Axis, then click "OK".
![VERDI_testing_issue_255_2](https://user-images.githubusercontent.com/73186639/177858069-214cf10b-5910-4515-a1cc-ed981445366a.png)
No scatter plot was displayed, the following error messages was shown in the command window. 
![VERDI_testing_issue_255_1](https://user-images.githubusercontent.com/73186639/177858220-131d06b9-1349-4aee-9a3d-43ebd5645a8f.png)

**Comment by lizadams** [comment]
Also tested with VERDI_2.1.4_win64_20220720.zip
Confirmed same error messages are generated when incrementing the timestep on the scatter plot.

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.4_linux64_20220809.tar.gz on Atmos, found that this issue has resolved.**
The scatter plot was correctly displayed when incrementing the timesteps, no error messages showed up in the command window.  
![VERDI_testing_issue_255_1](https://user-images.githubusercontent.com/73186639/183711695-bbe90f59-c808-41b3-8fdd-00c9043aa44c.png)
![VERDI_testing_issue_255_2](https://user-images.githubusercontent.com/73186639/183711717-360fc93f-5636-4e46-b724-d2275083ab32.png)

**Comment by yadongxuEPA** [comment]
**Retested with VERDI_2.1.4_linux64_20221007.tar.gz on Atmos , confirmed that this issue has resolved.**

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20231222.tar.gz on Atmos and it worked.

**Comment by lizadams** [comment]
I can do this within the VERDI gui using VERDI_2.1.5_mac_20240103.tar.gz, but I am getting an error using the command line option.  I am getting the following command line error on the mac:

./verdi.sh -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile -s "t2m[1]*2" -g tile -scatter "t2m[1]" "t2m[1]*2"
in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2024.01.03 21:19:43.973 [main] ERROR anl.verdi.core.VerdiPlugin - Error 
java.lang.IllegalArgumentException: Invalid call to DataFrameIndex.setXY( x = 1 ... )
	at anl.verdi.data.DataFrameIndex.setXY(DataFrameIndex.java:124) ~[?:?]
	at anl.verdi.plot.data.ScatterXYDataset$FrameData.getValue(ScatterXYDataset.java:79) ~[?:?]
	at anl.verdi.plot.data.ScatterXYDataset.getXValue(ScatterXYDataset.java:189) ~[?:?]
	at org.jfree.data.general.DatasetUtilities.iterateDomainBounds(DatasetUtilities.java:759) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.data.general.DatasetUtilities.findDomainBounds(DatasetUtilities.java:663) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.data.general.DatasetUtilities.findDomainBounds(DatasetUtilities.java:638) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.plot.XYPlot.getDataRange(XYPlot.java:4466) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.axis.NumberAxis.autoAdjustRange(NumberAxis.java:433) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.axis.NumberAxis.configure(NumberAxis.java:415) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.axis.Axis.setPlot(Axis.java:1043) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.plot.XYPlot.<init>(XYPlot.java:668) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.ChartFactory.createScatterPlot(ChartFactory.java:1692) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at anl.verdi.plot.types.ScatterPlot.createChart(ScatterPlot.java:375) ~[core.jar:?]
	at anl.verdi.plot.types.ScatterPlot.<init>(ScatterPlot.java:157) ~[core.jar:?]
	at anl.verdi.plot.types.ScatterPlot.<init>(ScatterPlot.java:134) ~[core.jar:?]
	at anl.verdi.plot.gui.PlotFactory.getScatterPlot(PlotFactory.java:56) ~[core.jar:?]
	at anl.verdi.plot.gui.ScatterPlotCreator.createPlotFromCommandLine(ScatterPlotCreator.java:93) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler$28.run(ScriptHandler.java:1019) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1525) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:167) ~[core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:168) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:178) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:388) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
Additional re-tests done on VERDI_2.1.4_linux64_20231013.tar.gz (before Java update) on Atmos and got the same error:
![image](https://github.com/CEMPD/VERDI/assets/73186639/cd9bcd2e-7af1-44d6-bef2-f9dc1294f170)

**Comment by lizadams** [comment]
Restested using 

You can create the gui and load the variables using

```
./verdi.command -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile -s "t2m[1]*2" -g tile 
```

Once in the GUI, you can select scatter plot, and then the formulas and create the plot, and no error is generated.


If you try to use the -scatter option and specify the formula, it fails with the following errror.

```
./verdi.command -f $cwd/data/model/t2m_only.nc -s "t2m[1]" -g tile -s "t2m[1]*2" -g tile -scatter "t2m[1]" "t2m[1]*2"
```

in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
2024.01.25 18:27:36.440 [main] ERROR anl.verdi.core.VerdiPlugin - Error 
java.lang.IllegalArgumentException: Invalid call to DataFrameIndex.setXY( x = 1 ... )
	at anl.verdi.data.DataFrameIndex.setXY(DataFrameIndex.java:124) ~[?:?]
	at anl.verdi.plot.data.ScatterXYDataset$FrameData.getValue(ScatterXYDataset.java:79) ~[?:?]
	at anl.verdi.plot.data.ScatterXYDataset.getXValue(ScatterXYDataset.java:189) ~[?:?]
	at org.jfree.data.general.DatasetUtilities.iterateDomainBounds(DatasetUtilities.java:759) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.data.general.DatasetUtilities.findDomainBounds(DatasetUtilities.java:663) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.data.general.DatasetUtilities.findDomainBounds(DatasetUtilities.java:638) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.plot.XYPlot.getDataRange(XYPlot.java:4466) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.axis.NumberAxis.autoAdjustRange(NumberAxis.java:433) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.axis.NumberAxis.configure(NumberAxis.java:415) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.axis.Axis.setPlot(Axis.java:1043) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.plot.XYPlot.<init>(XYPlot.java:668) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at org.jfree.chart.ChartFactory.createScatterPlot(ChartFactory.java:1692) ~[netcdfAll-4.5.5-SNAPSHOT.jar:?]
	at anl.verdi.plot.types.ScatterPlot.createChart(ScatterPlot.java:375) ~[core.jar:?]
	at anl.verdi.plot.types.ScatterPlot.<init>(ScatterPlot.java:157) ~[core.jar:?]
	at anl.verdi.plot.types.ScatterPlot.<init>(ScatterPlot.java:134) ~[core.jar:?]
	at anl.verdi.plot.gui.PlotFactory.getScatterPlot(PlotFactory.java:56) ~[core.jar:?]
	at anl.verdi.plot.gui.ScatterPlotCreator.createPlotFromCommandLine(ScatterPlotCreator.java:93) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler$28.run(ScriptHandler.java:1021) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1528) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:167) ~[core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:168) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:178) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:388) [saf.core.runtime.jar:?]

**Comment by yadongxuEPA** [comment]
**Re-tests done on VERDI_2.1.5_linux64_20240124.tar.gz on Atmos and got the same error, confirmed that the command line issue persists.** 
![image](https://github.com/CEMPD/VERDI/assets/73186639/68bab842-4fd6-49fd-a130-d39182126a2f)
