### ISSUE TITLE
Error while creating CRS for UTM Error in "PROJCS"

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#283]
**Describe the bug**
Using the test scripts available under VERDI_2.1/data/scripts using Version: 2.1 2021-09-20 I am getting the following error.
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "gridCRS" is null

**To Reproduce**
1. cd VERDI_2.1/data/scripts
2. change permissions for the scripts using the command: chmod 755 *.csh
3. run the script from the command line ./verdi_script.utm.csh
running verdi_script_utm.csh
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
2021.09.21 15:54:42.146 [main] ERROR anl.verdi.loaders.NetcdfBoxer - Error while creating CRS for UTM Error in "PROJCS": Unexpected end of string.
2021.09.21 15:54:42.190 [main] ERROR anl.verdi.loaders.NetcdfBoxer - Error while creating CRS for UTM Error in "PROJCS": Unexpected end of string.
2021.09.21 15:54:43.572 [main] ERROR anl.verdi.commandline.ScriptHandler - Error in ScriptHandler.dataMap.put 'SAVEIMAGE'
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "gridCRS" is null
	at anl.verdi.plot.gui.VerdiBoundaries.draw(VerdiBoundaries.java:157) ~[core.jar:?]
	at gov.epa.emvl.Mapper.draw(Mapper.java:168) ~[core.jar:?]
	at anl.verdi.plot.gui.FastTilePlot.drawBatchImage(FastTilePlot.java:865) ~[core.jar:?]
	at anl.verdi.plot.gui.FastTilePlot.exportImage(FastTilePlot.java:2571) ~[core.jar:?]
	at anl.verdi.commandline.ScriptHandler$27.run(ScriptHandler.java:967) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.handleOptions(ScriptHandler.java:1510) [core.jar:?]
	at anl.verdi.commandline.ScriptHandler.run(ScriptHandler.java:166) [core.jar:?]
	at anl.verdi.core.VerdiPlugin.run(VerdiPlugin.java:160) [core.jar:?]
	at saf.core.runtime.CorePlugin.runApplicationRunnable(CorePlugin.java:93) [saf.core.runtime.jar:?]
	at saf.core.runtime.CorePlugin.run(CorePlugin.java:48) [saf.core.runtime.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at saf.core.runtime.Boot.run(Boot.java:161) [saf.core.runtime.jar:?]
	at saf.core.runtime.Boot.main(Boot.java:354) [saf.core.runtime.jar:?]
ls: /applications/VERDI_2.1/data/plots/grid_pophous_utm.ncf.HOUSEHOLDS.png: No such file or directory
check output file: 

**Expected behavior**
I tested with the an older released version: Version: 2.0 2021-03-27 and it correctly created the plot:
check output file:  VERDI_2.0/data/plots/grid_pophous_utm.ncf.HOUSEHOLDS.png

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by lizadams** [comment]
Plot should look something like the followin
<img width="796" alt="Screen Shot 2021-09-21 at 4 18 56 PM" src="https://user-images.githubusercontent.com/1183863/134241678-de6590dc-37e2-4398-8c21-302e64aba220.png">
g

**Comment by yadongxuEPA** [comment]
**Retested this issue with VERDI_2.1_linux64_20211203.tar.gz, the issue has resolved.**
Running the script "verdi_script_utm.csh" was successful without error. 
![issue_283_testing_20211203_2](https://user-images.githubusercontent.com/73186639/144923723-33f0dede-a6cd-42b9-9563-3f9988dd8748.png)
![issue_283_testing_20211203_1](https://user-images.githubusercontent.com/73186639/144923763-4aa0ac22-0925-4538-b05b-2de9a94c48b8.png)
