### ISSUE TITLE
Saving/opening VERDI project

### ISSUE THREAD

**Issue by dkang2** [CEMPD/VERDI#318]
**Describe the bug**
On Linux machine, I have a few opened datasets and several formulas and want to save it as a project for later work. When I clicked File -> Save Project As, a pop-up window opened, and a directory and project name was given, then clicked Save. But when came back to the directory, the saved project file was not there. Neither I tried to open the project that was saved from the directory from VERDI GUI: File -> Open Project

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dkang2** [comment]
Just tested the 20230425 build. I was able to save a project onto file and the file does exist. But when I reopened verdi and tried to open the project, nothing happens.
![image](https://user-images.githubusercontent.com/15109047/234658954-700f7bc4-fdd0-478c-9f36-2a591697e88c.png)

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20230526 builds on Atmos, found that this issue has not resolved. No content was saved in the saved-project filename.**

**Comment by yadongxuEPA** [comment]
**Retested VERDI 2.1.4 20230831 builds on Atmos, found that this issue has resolved.**  Now "Save Project" and "Save Project As" work as described in the user manual. 

![issue_318_user_manual_1](https://github.com/CEMPD/VERDI/assets/73186639/96c1aec4-4d54-4141-bdad-db3559795588)
Step 1: load the saved project into VERDI
![issue_318_open_project](https://github.com/CEMPD/VERDI/assets/73186639/3024d6e2-b0dc-4c77-9ab9-b12fbc939dd0)
Step 2: check if the dataset was saved and loaded 
![issue_318_open_project_dataset](https://github.com/CEMPD/VERDI/assets/73186639/eb24c9f8-8ccf-48b5-9d00-4f4224c279b9)
Step 3: check if the formula was saved and loaded 
![issue_318_open_project_formulas](https://github.com/CEMPD/VERDI/assets/73186639/eed84dda-5698-4cc4-a69a-148b398330bd)

**Comment by dkang2** [comment]
The VERDI 2.1.4 20230911 build seems reversed earlier fix for this problem. The project is saved, but when re-open it, nothing happens, no contents.

**Comment by dkang2** [comment]
In fact, the "Save Project As" function doesn't work either with the 20230911 build with the following error message:

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collectionseeMapConverter
        at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:807)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:350)
        at anl.verdi.io.IO.save(IO.java:115)
        at anl.verdi.core.VerdiApplication.doSave(VerdiApplication.java:349)
        at anl.verdi.core.VerdiApplication.saveProjectAs(VerdiApplication.java:364)
        at anl.verdi.core.action.SaveAsAction.actionPerformed(SaveAsAction.java:25)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by dkang2** [comment]
The issue was resolved. It now successfully saves and opens project as expected.

**Comment by yadongxuEPA** [comment]
Retested VERDI 2.1.4 20230911 builds on Atmos, confirmed that this issue has resolved.

**Comment by yadongxuEPA** [comment]
**Retested VERDI 20231012 builds on Atmos, confirmed that this issue has resolved.**

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20231222.tar.gz on Atmos and it worked.

**Comment by lizadams** [comment]
Testing using VERDI_2.1.5_mac_20240103.tar.gz

using command line option: fails to recognize -project

./verdi.command -project "~/test_project"
2024.01.04 18:20:36.350 [main] ERROR anl.verdi.commandline.ScriptHandler - -project is not a valid command.  Skipping this command...

But the verdi.sh -help command documentation says it is:

./verdi.command -help
[ -project "<VERDIProjectName>"]

Using the VERDI GUI - I was able to load the project and verify that the dataset and the variable was loaded.

**Comment by yadongxuEPA** [comment]
Checked VERDI_2.1.5_linux64_20240103.tar.gz on Atmos with command line, got the same error as below:
![image](https://github.com/CEMPD/VERDI/assets/73186639/eda09489-f5fb-4753-b176-012c2852bde0)

**Comment by yadongxuEPA** [comment]
Additional re-test also done on VERDI_2.1.4_linux64_20231013.tar.gz (before Java update) on Atmos with command line, got the same error as below:
![image](https://github.com/CEMPD/VERDI/assets/73186639/59676bf8-aa67-4519-a735-3d8e2c5c58d6)

**Comment by lizadams** [comment]
Verified by creating a new saved project that saved the filename and variable O3

```
cat ~/o3_CCTM46_save_project
```

Output

```
<project>
  <datasetElements>
    <dataset.element>
      <timeMin>0</timeMin>
      <timeMax>24</timeMax>
      <layerMin>0</layerMin>
      <layerMax>2</layerMax>
      <timeUsed>false</timeUsed>
      <layerUsed>false</layerUsed>
      <datasetURL>file:/Users/lizadams/Downloads/VERDI_2.1.5_01_24/plugins/bootstrap/../../data/model/CCTM46_P16.baseO2a.36k.O3MAX</datasetURL>
      <alias>[1]</alias>
      <urlIndex>1</urlIndex>
    </dataset.element>
  </datasetElements>
  <formulaElements>
    <formula.element>
      <timeMin>0</timeMin>
      <timeMax>24</timeMax>
      <layerMin>-1</layerMin>
      <layerMax>0</layerMax>
      <timeUsed>false</timeUsed>
      <layerUsed>false</layerUsed>
      <formula>O3[1]</formula>
    </formula.element>
  </formulaElements>
```
Note, that the project file contains the path to the file and filename, and the formula name.

Verified that you could load the project and find the filename and formula name in the gui after loading.

Using VERDI_2.1.5_mac_20240124.tar.gz

[vcredadmins-MacBook-Pro:~/downloads/VERDI_2.1.5_01_24] lizadams% 

```
cd /Users/lizadams/downloads/VERDI_2.1.5_01_24
./verdi.command -project ~/o3_CCTM46_save_project
```

This was successful.
It loaded the project.

**Comment by yadongxuEPA** [comment]
**Checked VERDI_2.1.5_linux64_20240124.tar.gz on Atmos  and confirmed that the command line issue has resolved.**
