### ISSUE TITLE
script animatedGIF not working with -quit command

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#86]
Talat and Yongtao reported an error with creating multiple animatedGIF files using a script.
I get the following error when I run the following script (using either 1.5.0 or 1.6.0_alpha)
It looks like the script is handled by
verdi_core/src/anl/verdi/commandline/ScriptHandler.java            (command line scripting)
NOTE, if I add a -quit at the end then the animated plot isn't created as the quit is executed before the animated gif is completed.
# !/bin/csh -f

setenv INDIR /applications/VERDI_1.5.0/data/model
setenv OUTDIR /Users/lizadams/VERDI/bugs/talat/outdir
cd /applications/VERDI_1.5.0/
./verdi.command \
"-f $INDIR/CCTM47_aac_spr06.12k.CONC.2006113.O3.ncf \
 -s O3[1]*1000 \
 -g tile \
 -tinit 0 \
 -tfinal 23 \
 -animatedGIF $OUTDIR/movie_hourly.gif "

java.lang.IllegalArgumentException: image == null!
    at javax.imageio.ImageTypeSpecifier.<init>(ImageTypeSpecifier.java:128)
    at anl.verdi.plot.util.WriteAnimatedGif.addFrame(WriteAnimatedGif.java:160)
    at anl.verdi.plot.anim.PlotAnimator$UpdatePlotAction.actionPerformed(PlotAnimator.java:198)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

If I add a -quit command at the end of the script then the animated GIF output file doesn't have time to be created.
Alison suggested adding -system `sleep 2` command, but I can't get that to work because it appears to sleep before the animateGIF process begins.  This is due to the threading - the sleep command is on the main thread, while the drawing is occurring on Thread 4: 
12:42:08.273 [Thread-4] DEBUG anl.verdi.plot.gui.FastTilePlot - within drawMode != DRAW_NONE && !VerdiGUI.isHidden((Plot) threadParent)
I've created two new scripts in Eclipse:
verdi_script_saveImage.launch  - this script demonstrates that -quit works for the saveImage command
verdi_script_animatedGIF.launch - this script demonstrates that -quit doesn't work for animatedGIF command

**Comment by lizadams** [comment]
this topic has been more recently tested and documented as in issue #148 
closing this one.
