### ISSUE TITLE
contour plot - mpas history file error

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#96]
I am able to create a contour plot using the shapefile_mpas compiled version (running outside of eclipse) for the O3 variable from the CCTM46_P16.base02a.36k.O3MAX file.
![cctm46_o3_contour_plot](https://cloud.githubusercontent.com/assets/1183863/17150085/0de36bb8-533c-11e6-98fd-6e19cb7feb09.png)
However, when I try to use the contour plot of the SMOIS variable from the MPAS file history.2013-07-17.nc, it crashes and gives the following stack trace.
Elizabeth-Adamss-MacBook-Pro:VERDI_1.6.0_shapefile_mpas lizadams$ ./verdi.command
Variable indexToVertexID not found, not MPAS
3D [dev] 1.6.0-pre10-daily-experimental daily

in netcdfdataset.java openDataset 1 arguments
in netcdfdataset.java openDataset 3 arguments
in netcdfdataset.java ready to return openDataset 5 arguments
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at anl.verdi.plot.types.Contour3D.createData(Contour3D.java:503)
    at anl.verdi.plot.types.Contour3D.<init>(Contour3D.java:171)
    at anl.verdi.plot.gui.PlotFactory.getPlot(PlotFactory.java:95)
    at anl.verdi.plot.gui.PlotFactory.getPlot(PlotFactory.java:78)
    at anl.verdi.plot.gui.DefaultPlotCreator.doCreatePlot(DefaultPlotCreator.java:48)
    at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39)
    at anl.verdi.plot.gui.action.Contour3DPlot.actionPerformed(Contour3DPlot.java:22)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lizadams** [comment]
- [x] QA check to verify that SMOIS variable from the MPAS file
verified that I am able to create a 3D plot of this variable.
