### ISSUE TITLE
vertical cross section plot error - SH20 variable in mpas history file

### ISSUE THREAD

**Issue by lizadams** [CEMPD/VERDI#98]
Error when selecting the vertical cross section plot for the sh20 variable in the history.2013-07-17.nc file.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at anl.verdi.plot.gui.VerticalCrossDialog.init(VerticalCrossDialog.java:108)
    at anl.verdi.plot.gui.VerticalCrossPlotCreator.doCreatePlot(VerticalCrossPlotCreator.java:63)
    at anl.verdi.plot.gui.AbstractPlotCreator.createPlot(AbstractPlotCreator.java:39)
    at anl.verdi.plot.gui.action.VerticalCrossSection.actionPerformed(VerticalCrossSection.java:21)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lizadams** [comment]
using VERDI_2.0_beta_linux64_20190623.tar.gz
```
#!/bin/csh -f

#script for testing command line options

echo 'running verdi_script_mpas.csh'
setenv verdi_dir /proj/ie/apps/longleaf/VERDI_2.0_jun_23/VERDI_2.0_beta
cd $verdi_dir

foreach species ( sh2o )
./verdi.sh \
         -f $verdi_dir/data/model/history.2013-07-10.nc \
         -s "${species}[1]" \
         -g tile \
#          -quit
          echo 'check outputfile' `ls -lrt $verdi_dir/test.$species.png`
        
 end
```
I am able to get a vertical cross section plot using the sh2o variable, but I am not sure what it should look like.

<img width="1227" alt="Screen Shot 2019-06-24 at 7 10 12 PM" src="https://user-images.githubusercontent.com/1183863/60057767-bca8c400-96b3-11e9-9a2b-dd3ad6145af4.png">
Tile Plot of sh20
<img width="998" alt="Screen Shot 2019-06-24 at 7 10 42 PM" src="https://user-images.githubusercontent.com/1183863/60057784-cd593a00-96b3-11e9-820a-76e7e0e7466b.png">
